set(CTEST_PROJECT_NAME "gentest")
set(CTEST_NIGHTLY_START_TIME "00:00:00 UTC")

if(DEFINED ENV{GENTEST_CDASH_SUBMIT_URL} AND NOT "$ENV{GENTEST_CDASH_SUBMIT_URL}" STREQUAL "")
    set(CTEST_SUBMIT_URL "$ENV{GENTEST_CDASH_SUBMIT_URL}")
endif()
