include_guard(GLOBAL)

function(_gentest_mock_backends out_backends)
    set(${out_backends} gentest gmock trompeloeil PARENT_SCOPE)
endfunction()

function(_gentest_third_party_mock_backends out_backends)
    set(${out_backends} gmock trompeloeil PARENT_SCOPE)
endfunction()

function(_gentest_mock_backend_list out_list)
    _gentest_mock_backends(_gentest_supported_backends)
    string(JOIN ", " _gentest_backend_list ${_gentest_supported_backends})
    set(${out_list} "${_gentest_backend_list}" PARENT_SCOPE)
endfunction()

function(_gentest_normalize_mock_backend raw_backend option_label out_backend)
    if("${raw_backend}" STREQUAL "")
        set(_gentest_backend "gentest")
    else()
        string(TOLOWER "${raw_backend}" _gentest_backend)
    endif()

    _gentest_mock_backends(_gentest_supported_backends)
    if(NOT _gentest_backend IN_LIST _gentest_supported_backends)
        _gentest_mock_backend_list(_gentest_backend_list)
        message(FATAL_ERROR "${option_label} must be one of: ${_gentest_backend_list}; got '${raw_backend}'")
    endif()
    set(${out_backend} "${_gentest_backend}" PARENT_SCOPE)
endfunction()

function(_gentest_is_third_party_mock_backend backend out_result)
    _gentest_third_party_mock_backends(_gentest_third_party_backends)
    if("${backend}" IN_LIST _gentest_third_party_backends)
        set(${out_result} TRUE PARENT_SCOPE)
    else()
        set(${out_result} FALSE PARENT_SCOPE)
    endif()
endfunction()
