include_guard(GLOBAL)

function(_gentest_collect_codegen_dep_targets_from_link_graph target out_targets)
    set(_gentest_result "")
    set(_gentest_explicit_mock_targets "")
    set(_gentest_queue "${target}")
    set(_gentest_seen "")

    while(_gentest_queue)
        list(POP_FRONT _gentest_queue _gentest_current)
        if(NOT TARGET "${_gentest_current}")
            continue()
        endif()

        get_target_property(_gentest_alias_target "${_gentest_current}" ALIASED_TARGET)
        if(_gentest_alias_target AND NOT _gentest_alias_target STREQUAL "_gentest_alias_target-NOTFOUND")
            set(_gentest_current "${_gentest_alias_target}")
        endif()

        list(FIND _gentest_seen "${_gentest_current}" _gentest_seen_index)
        if(NOT _gentest_seen_index EQUAL -1)
            continue()
        endif()
        list(APPEND _gentest_seen "${_gentest_current}")

        if(NOT _gentest_current STREQUAL "${target}")
            get_target_property(_gentest_is_explicit_mock "${_gentest_current}" GENTEST_EXPLICIT_MOCK_TARGET)
            if(_gentest_is_explicit_mock)
                get_target_property(_gentest_explicit_codegen_dep "${_gentest_current}" GENTEST_CODEGEN_DEP_TARGET)
                if(_gentest_explicit_codegen_dep AND NOT _gentest_explicit_codegen_dep MATCHES "-NOTFOUND$")
                    list(APPEND _gentest_result "${_gentest_explicit_codegen_dep}")
                endif()
                list(APPEND _gentest_result "${_gentest_current}")
                list(APPEND _gentest_explicit_mock_targets "${_gentest_current}")
            endif()
        endif()

        foreach(_gentest_link_prop IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_gentest_link_deps "${_gentest_current}" "${_gentest_link_prop}")
            if(NOT _gentest_link_deps OR _gentest_link_deps MATCHES "-NOTFOUND$")
                continue()
            endif()
            foreach(_gentest_link_dep IN LISTS _gentest_link_deps)
                if("${_gentest_link_dep}" STREQUAL "" OR "${_gentest_link_dep}" MATCHES "\\$<")
                    continue()
                endif()
                if(TARGET "${_gentest_link_dep}")
                    list(APPEND _gentest_queue "${_gentest_link_dep}")
                endif()
            endforeach()
        endforeach()
    endwhile()

    list(REMOVE_DUPLICATES _gentest_result)
    set(${out_targets} "${_gentest_result}" PARENT_SCOPE)
    if(ARGC GREATER 2)
        list(REMOVE_DUPLICATES _gentest_explicit_mock_targets)
        set(${ARGV2} "${_gentest_explicit_mock_targets}" PARENT_SCOPE)
    endif()
endfunction()

function(_gentest_target_has_module_metadata target out_has_modules)
    set(_gentest_has_modules FALSE)
    if(TARGET "${target}")
        get_target_property(_gentest_scan_for_modules "${target}" CXX_SCAN_FOR_MODULES)
        if(_gentest_scan_for_modules AND NOT _gentest_scan_for_modules MATCHES "-NOTFOUND$")
            set(_gentest_has_modules TRUE)
        endif()
        foreach(_gentest_module_prop IN ITEMS
                CXX_MODULE_SETS
                INTERFACE_CXX_MODULE_SETS
                GENTEST_EXPLICIT_MOCK_MODULE_BUILD_SOURCES
                GENTEST_EXPLICIT_MOCK_MODULE_REL_SOURCES)
            if(_gentest_has_modules)
                break()
            endif()
            get_target_property(_gentest_module_values "${target}" "${_gentest_module_prop}")
            if(_gentest_module_values AND NOT _gentest_module_values MATCHES "-NOTFOUND$")
                set(_gentest_has_modules TRUE)
                break()
            endif()
        endforeach()
    endif()
    set(${out_has_modules} "${_gentest_has_modules}" PARENT_SCOPE)
endfunction()

function(_gentest_link_graph_has_explicit_mock_module_context target out_has_modules)
    set(_gentest_has_modules FALSE)
    set(_gentest_queue "${target}")
    set(_gentest_seen "")

    while(_gentest_queue)
        list(POP_FRONT _gentest_queue _gentest_current)
        if(NOT TARGET "${_gentest_current}")
            continue()
        endif()

        get_target_property(_gentest_alias_target "${_gentest_current}" ALIASED_TARGET)
        if(_gentest_alias_target AND NOT _gentest_alias_target MATCHES "-NOTFOUND$")
            set(_gentest_current "${_gentest_alias_target}")
        endif()

        list(FIND _gentest_seen "${_gentest_current}" _gentest_seen_index)
        if(NOT _gentest_seen_index EQUAL -1)
            continue()
        endif()
        list(APPEND _gentest_seen "${_gentest_current}")

        if(NOT _gentest_current STREQUAL "${target}")
            get_target_property(_gentest_is_explicit_mock "${_gentest_current}" GENTEST_EXPLICIT_MOCK_TARGET)
            if(_gentest_is_explicit_mock)
                _gentest_target_has_module_metadata("${_gentest_current}" _gentest_current_has_modules)
                if(_gentest_current_has_modules)
                    set(_gentest_has_modules TRUE)
                    break()
                endif()
            endif()
        endif()

        foreach(_gentest_link_prop IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_gentest_link_deps "${_gentest_current}" "${_gentest_link_prop}")
            if(NOT _gentest_link_deps OR _gentest_link_deps MATCHES "-NOTFOUND$")
                continue()
            endif()
            foreach(_gentest_link_dep IN LISTS _gentest_link_deps)
                if("${_gentest_link_dep}" STREQUAL "" OR "${_gentest_link_dep}" MATCHES "\\$<")
                    continue()
                endif()
                if(TARGET "${_gentest_link_dep}")
                    list(APPEND _gentest_queue "${_gentest_link_dep}")
                endif()
            endforeach()
        endforeach()
    endwhile()

    set(${out_has_modules} "${_gentest_has_modules}" PARENT_SCOPE)
endfunction()
