include_guard(GLOBAL)

function(_gentest_collect_scan_include_dirs target source out_dirs)
    set(_gentest_dirs "")

    foreach(_gentest_prop IN ITEMS INCLUDE_DIRECTORIES SYSTEM_INCLUDE_DIRECTORIES)
        get_target_property(_gentest_prop_values ${target} ${_gentest_prop})
        if(NOT _gentest_prop_values STREQUAL "NOTFOUND" AND NOT _gentest_prop_values MATCHES "-NOTFOUND$")
            foreach(_gentest_dir IN LISTS _gentest_prop_values)
                if("${_gentest_dir}" MATCHES "\\$<")
                    continue()
                endif()
                get_filename_component(_gentest_abs_dir "${_gentest_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
                list(APPEND _gentest_dirs "${_gentest_abs_dir}")
            endforeach()
        endif()
    endforeach()

    get_source_file_property(_gentest_source_include_dirs "${source}" INCLUDE_DIRECTORIES)
    if(NOT _gentest_source_include_dirs STREQUAL "NOTFOUND" AND NOT _gentest_source_include_dirs MATCHES "-NOTFOUND$")
        foreach(_gentest_dir IN LISTS _gentest_source_include_dirs)
            if("${_gentest_dir}" MATCHES "\\$<")
                continue()
            endif()
            get_filename_component(_gentest_abs_dir "${_gentest_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            list(APPEND _gentest_dirs "${_gentest_abs_dir}")
        endforeach()
    endif()

    set(_gentest_expect_include_dir FALSE)
    foreach(_gentest_arg IN LISTS ARGN)
        if(_gentest_expect_include_dir)
            set(_gentest_expect_include_dir FALSE)
            if(NOT "${_gentest_arg}" MATCHES "\\$<")
                get_filename_component(_gentest_abs_dir "${_gentest_arg}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
                list(APPEND _gentest_dirs "${_gentest_abs_dir}")
            endif()
            continue()
        endif()

        if(_gentest_arg STREQUAL "-I" OR _gentest_arg STREQUAL "-isystem" OR _gentest_arg STREQUAL "-iquote" OR
           _gentest_arg STREQUAL "-idirafter" OR _gentest_arg STREQUAL "/I")
            set(_gentest_expect_include_dir TRUE)
            continue()
        endif()

        set(_gentest_joined_prefixes "-I" "-isystem" "-iquote" "-idirafter" "/I")
        foreach(_gentest_prefix IN LISTS _gentest_joined_prefixes)
            string(LENGTH "${_gentest_prefix}" _gentest_prefix_len)
            string(SUBSTRING "${_gentest_arg}" 0 ${_gentest_prefix_len} _gentest_arg_prefix)
            if(_gentest_arg_prefix STREQUAL _gentest_prefix)
                string(SUBSTRING "${_gentest_arg}" ${_gentest_prefix_len} -1 _gentest_dir)
                if(NOT "${_gentest_dir}" STREQUAL "" AND NOT "${_gentest_dir}" MATCHES "\\$<")
                    get_filename_component(_gentest_abs_dir "${_gentest_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
                    list(APPEND _gentest_dirs "${_gentest_abs_dir}")
                endif()
                break()
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _gentest_dirs)
    set(${out_dirs} "${_gentest_dirs}" PARENT_SCOPE)
endfunction()

function(_gentest_collect_scan_include_dirs_from_sequence base_dir out_dirs)
    set(_gentest_dirs "")
    set(_gentest_expect_include_dir FALSE)
    foreach(_gentest_arg IN LISTS ARGN)
        if(_gentest_expect_include_dir)
            set(_gentest_expect_include_dir FALSE)
            if(NOT "${_gentest_arg}" MATCHES "\\$<")
                get_filename_component(_gentest_abs_dir "${_gentest_arg}" ABSOLUTE BASE_DIR "${base_dir}")
                list(APPEND _gentest_dirs "${_gentest_abs_dir}")
            endif()
            continue()
        endif()

        if(_gentest_arg STREQUAL "-I" OR _gentest_arg STREQUAL "-isystem" OR _gentest_arg STREQUAL "-iquote" OR
           _gentest_arg STREQUAL "-idirafter" OR _gentest_arg STREQUAL "/I")
            set(_gentest_expect_include_dir TRUE)
            continue()
        endif()

        set(_gentest_joined_prefixes "-I" "-isystem" "-iquote" "-idirafter" "/I")
        foreach(_gentest_prefix IN LISTS _gentest_joined_prefixes)
            string(LENGTH "${_gentest_prefix}" _gentest_prefix_len)
            string(SUBSTRING "${_gentest_arg}" 0 ${_gentest_prefix_len} _gentest_arg_prefix)
            if(_gentest_arg_prefix STREQUAL _gentest_prefix)
                string(SUBSTRING "${_gentest_arg}" ${_gentest_prefix_len} -1 _gentest_dir)
                if(NOT "${_gentest_dir}" STREQUAL "" AND NOT "${_gentest_dir}" MATCHES "\\$<")
                    get_filename_component(_gentest_abs_dir "${_gentest_dir}" ABSOLUTE BASE_DIR "${base_dir}")
                    list(APPEND _gentest_dirs "${_gentest_abs_dir}")
                endif()
                break()
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _gentest_dirs)
    set(${out_dirs} "${_gentest_dirs}" PARENT_SCOPE)
endfunction()

function(_gentest_collect_scan_macro_args_from_sequence out_args out_has_genex)
    set(_gentest_args "")
    set(_gentest_has_genex FALSE)
    set(_gentest_expect_define FALSE)
    set(_gentest_expect_undef FALSE)
    foreach(_gentest_arg IN LISTS ARGN)
        if(_gentest_expect_define)
            if("${_gentest_arg}" MATCHES "\\$<")
                set(_gentest_has_genex TRUE)
                set(_gentest_expect_define FALSE)
                continue()
            endif()
            list(APPEND _gentest_args -D "${_gentest_arg}")
            set(_gentest_expect_define FALSE)
            continue()
        endif()
        if(_gentest_expect_undef)
            if("${_gentest_arg}" MATCHES "\\$<")
                set(_gentest_has_genex TRUE)
                set(_gentest_expect_undef FALSE)
                continue()
            endif()
            list(APPEND _gentest_args -U "${_gentest_arg}")
            set(_gentest_expect_undef FALSE)
            continue()
        endif()

        if(_gentest_arg STREQUAL "-D" OR _gentest_arg STREQUAL "/D")
            set(_gentest_expect_define TRUE)
            continue()
        endif()
        if(_gentest_arg STREQUAL "-U" OR _gentest_arg STREQUAL "/U")
            set(_gentest_expect_undef TRUE)
            continue()
        endif()
        if(_gentest_arg MATCHES "^[-/]D.+$")
            if("${_gentest_arg}" MATCHES "\\$<")
                set(_gentest_has_genex TRUE)
                continue()
            endif()
            list(APPEND _gentest_args "${_gentest_arg}")
            continue()
        endif()
        if(_gentest_arg MATCHES "^[-/]U.+$")
            if("${_gentest_arg}" MATCHES "\\$<")
                set(_gentest_has_genex TRUE)
                continue()
            endif()
            list(APPEND _gentest_args "${_gentest_arg}")
        endif()
    endforeach()

    set(${out_args} "${_gentest_args}" PARENT_SCOPE)
    set(${out_has_genex} "${_gentest_has_genex}" PARENT_SCOPE)
endfunction()

function(_gentest_collect_scan_macro_args target source out_args out_has_genex)
    set(_gentest_definition_props COMPILE_DEFINITIONS)
    if(NOT CMAKE_CONFIGURATION_TYPES AND CMAKE_BUILD_TYPE)
        set(_gentest_configs ${CMAKE_BUILD_TYPE})
    else()
        set(_gentest_configs "")
    endif()
    foreach(_cfg IN LISTS _gentest_configs)
        string(TOUPPER "${_cfg}" _cfg_upper)
        list(APPEND _gentest_definition_props "COMPILE_DEFINITIONS_${_cfg_upper}")
    endforeach()
    list(REMOVE_DUPLICATES _gentest_definition_props)

    set(_gentest_args "")
    set(_gentest_has_genex FALSE)
    foreach(_gentest_prop IN LISTS _gentest_definition_props)
        get_target_property(_gentest_target_defs ${target} ${_gentest_prop})
        if(NOT _gentest_target_defs STREQUAL "NOTFOUND" AND NOT _gentest_target_defs MATCHES "-NOTFOUND$")
            foreach(_gentest_def IN LISTS _gentest_target_defs)
                if("${_gentest_def}" MATCHES "\\$<")
                    continue()
                endif()
                list(APPEND _gentest_args "-D${_gentest_def}")
            endforeach()
        endif()

        get_source_file_property(_gentest_source_defs "${source}" ${_gentest_prop})
        if(NOT _gentest_source_defs STREQUAL "NOTFOUND" AND NOT _gentest_source_defs MATCHES "-NOTFOUND$")
            foreach(_gentest_def IN LISTS _gentest_source_defs)
                if("${_gentest_def}" MATCHES "\\$<")
                    continue()
                endif()
                list(APPEND _gentest_args "-D${_gentest_def}")
            endforeach()
        endif()
    endforeach()

    _gentest_collect_scan_macro_args_from_sequence(_gentest_argn_args _gentest_argn_has_genex ${ARGN})
    list(APPEND _gentest_args ${_gentest_argn_args})
    if(_gentest_argn_has_genex)
        set(_gentest_has_genex TRUE)
    endif()
    set(${out_args} "${_gentest_args}" PARENT_SCOPE)
    set(${out_has_genex} "${_gentest_has_genex}" PARENT_SCOPE)
endfunction()

function(_gentest_collect_codegen_dep_targets_from_link_graph target out_targets)
    set(_gentest_result "")
    set(_gentest_explicit_mock_targets "")
    set(_gentest_queue "${target}")
    set(_gentest_seen "")

    while(_gentest_queue)
        list(POP_FRONT _gentest_queue _gentest_current)
        if(NOT TARGET "${_gentest_current}")
            continue()
        endif()

        get_target_property(_gentest_alias_target "${_gentest_current}" ALIASED_TARGET)
        if(_gentest_alias_target AND NOT _gentest_alias_target STREQUAL "_gentest_alias_target-NOTFOUND")
            set(_gentest_current "${_gentest_alias_target}")
        endif()

        list(FIND _gentest_seen "${_gentest_current}" _gentest_seen_index)
        if(NOT _gentest_seen_index EQUAL -1)
            continue()
        endif()
        list(APPEND _gentest_seen "${_gentest_current}")

        if(NOT _gentest_current STREQUAL "${target}")
            get_target_property(_gentest_is_explicit_mock "${_gentest_current}" GENTEST_EXPLICIT_MOCK_TARGET)
            if(_gentest_is_explicit_mock)
                get_target_property(_gentest_explicit_codegen_dep "${_gentest_current}" GENTEST_CODEGEN_DEP_TARGET)
                if(_gentest_explicit_codegen_dep AND NOT _gentest_explicit_codegen_dep MATCHES "-NOTFOUND$")
                    list(APPEND _gentest_result "${_gentest_explicit_codegen_dep}")
                endif()
                list(APPEND _gentest_result "${_gentest_current}")
                list(APPEND _gentest_explicit_mock_targets "${_gentest_current}")
            endif()
        endif()

        foreach(_gentest_link_prop IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_gentest_link_deps "${_gentest_current}" "${_gentest_link_prop}")
            if(NOT _gentest_link_deps OR _gentest_link_deps MATCHES "-NOTFOUND$")
                continue()
            endif()
            foreach(_gentest_link_dep IN LISTS _gentest_link_deps)
                if("${_gentest_link_dep}" STREQUAL "" OR "${_gentest_link_dep}" MATCHES "\\$<")
                    continue()
                endif()
                if(TARGET "${_gentest_link_dep}")
                    list(APPEND _gentest_queue "${_gentest_link_dep}")
                endif()
            endforeach()
        endforeach()
    endwhile()

    list(REMOVE_DUPLICATES _gentest_result)
    set(${out_targets} "${_gentest_result}" PARENT_SCOPE)
    if(ARGC GREATER 2)
        list(REMOVE_DUPLICATES _gentest_explicit_mock_targets)
        set(${ARGV2} "${_gentest_explicit_mock_targets}" PARENT_SCOPE)
    endif()
endfunction()

function(_gentest_target_has_module_metadata target out_has_modules)
    set(_gentest_has_modules FALSE)
    if(TARGET "${target}")
        get_target_property(_gentest_scan_for_modules "${target}" CXX_SCAN_FOR_MODULES)
        if(_gentest_scan_for_modules AND NOT _gentest_scan_for_modules MATCHES "-NOTFOUND$")
            set(_gentest_has_modules TRUE)
        endif()
        foreach(_gentest_module_prop IN ITEMS
                CXX_MODULE_SETS
                INTERFACE_CXX_MODULE_SETS
                GENTEST_EXPLICIT_MOCK_MODULE_BUILD_SOURCES
                GENTEST_EXPLICIT_MOCK_MODULE_REL_SOURCES)
            if(_gentest_has_modules)
                break()
            endif()
            get_target_property(_gentest_module_values "${target}" "${_gentest_module_prop}")
            if(_gentest_module_values AND NOT _gentest_module_values MATCHES "-NOTFOUND$")
                set(_gentest_has_modules TRUE)
                break()
            endif()
        endforeach()
    endif()
    set(${out_has_modules} "${_gentest_has_modules}" PARENT_SCOPE)
endfunction()

function(_gentest_link_graph_has_explicit_mock_module_context target out_has_modules)
    set(_gentest_has_modules FALSE)
    set(_gentest_queue "${target}")
    set(_gentest_seen "")

    while(_gentest_queue)
        list(POP_FRONT _gentest_queue _gentest_current)
        if(NOT TARGET "${_gentest_current}")
            continue()
        endif()

        get_target_property(_gentest_alias_target "${_gentest_current}" ALIASED_TARGET)
        if(_gentest_alias_target AND NOT _gentest_alias_target MATCHES "-NOTFOUND$")
            set(_gentest_current "${_gentest_alias_target}")
        endif()

        list(FIND _gentest_seen "${_gentest_current}" _gentest_seen_index)
        if(NOT _gentest_seen_index EQUAL -1)
            continue()
        endif()
        list(APPEND _gentest_seen "${_gentest_current}")

        if(NOT _gentest_current STREQUAL "${target}")
            get_target_property(_gentest_is_explicit_mock "${_gentest_current}" GENTEST_EXPLICIT_MOCK_TARGET)
            if(_gentest_is_explicit_mock)
                _gentest_target_has_module_metadata("${_gentest_current}" _gentest_current_has_modules)
                if(_gentest_current_has_modules)
                    set(_gentest_has_modules TRUE)
                    break()
                endif()
            endif()
        endif()

        foreach(_gentest_link_prop IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_gentest_link_deps "${_gentest_current}" "${_gentest_link_prop}")
            if(NOT _gentest_link_deps OR _gentest_link_deps MATCHES "-NOTFOUND$")
                continue()
            endif()
            foreach(_gentest_link_dep IN LISTS _gentest_link_deps)
                if("${_gentest_link_dep}" STREQUAL "" OR "${_gentest_link_dep}" MATCHES "\\$<")
                    continue()
                endif()
                if(TARGET "${_gentest_link_dep}")
                    list(APPEND _gentest_queue "${_gentest_link_dep}")
                endif()
            endforeach()
        endforeach()
    endwhile()

    set(${out_has_modules} "${_gentest_has_modules}" PARENT_SCOPE)
endfunction()

