if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "gentest: compilation database does not exist: '${INPUT}'")
endif()
if(NOT DEFINED OUTPUT OR "${OUTPUT}" STREQUAL "")
    message(FATAL_ERROR "gentest: staged compilation database OUTPUT is required")
endif()
if(NOT DEFINED STAMP OR "${STAMP}" STREQUAL "")
    message(FATAL_ERROR "gentest: staged compilation database STAMP is required")
endif()
if(NOT DEFINED CHECK_STAMP OR "${CHECK_STAMP}" STREQUAL "")
    message(FATAL_ERROR "gentest: staged compilation database CHECK_STAMP is required")
endif()

file(READ "${INPUT}" _gentest_compdb_content)
get_filename_component(_gentest_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_gentest_output_dir}")

set(_gentest_update_output TRUE)
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _gentest_existing_compdb_content)
    if("${_gentest_existing_compdb_content}" STREQUAL "${_gentest_compdb_content}")
        set(_gentest_update_output FALSE)
    endif()
endif()
if(_gentest_update_output)
    string(RANDOM LENGTH 12 ALPHABET "0123456789abcdef" _gentest_output_suffix)
    set(_gentest_tmp_output "${OUTPUT}.tmp.${_gentest_output_suffix}")
    file(WRITE "${_gentest_tmp_output}" "${_gentest_compdb_content}")
    file(RENAME "${_gentest_tmp_output}" "${OUTPUT}" RESULT _gentest_output_rename_result)
    if(NOT _gentest_output_rename_result STREQUAL "0")
        file(REMOVE "${_gentest_tmp_output}")
        message(FATAL_ERROR
            "gentest: failed to atomically update staged compilation database '${OUTPUT}': ${_gentest_output_rename_result}")
    endif()
endif()

file(SHA256 "${INPUT}" _gentest_compdb_sha256)
set(_gentest_stamp_content "gentest.compdb.v1\n${_gentest_compdb_sha256}\n")
set(_gentest_update_stamp TRUE)
if(EXISTS "${STAMP}")
    file(READ "${STAMP}" _gentest_existing_stamp_content)
    if("${_gentest_existing_stamp_content}" STREQUAL "${_gentest_stamp_content}")
        set(_gentest_update_stamp FALSE)
    endif()
endif()
if(_gentest_update_stamp)
    string(RANDOM LENGTH 12 ALPHABET "0123456789abcdef" _gentest_stamp_suffix)
    set(_gentest_tmp_stamp "${STAMP}.tmp.${_gentest_stamp_suffix}")
    file(WRITE "${_gentest_tmp_stamp}" "${_gentest_stamp_content}")
    file(RENAME "${_gentest_tmp_stamp}" "${STAMP}" RESULT _gentest_stamp_rename_result)
    if(NOT _gentest_stamp_rename_result STREQUAL "0")
        file(REMOVE "${_gentest_tmp_stamp}")
        message(FATAL_ERROR
            "gentest: failed to atomically update compilation database stamp '${STAMP}': ${_gentest_stamp_rename_result}")
    endif()
endif()

# This stamp records that the current raw compilation database was examined.
# It intentionally changes even when STAMP does not, preventing Makefile
# generators from rerunning this staging command on every settled no-op build.
file(TOUCH "${CHECK_STAMP}")
