#pragma once

#include <string_view>

namespace gentest::codegen::tpl::mocks {

inline constexpr std::string_view registry_preamble = R"CPP(// This file is auto-generated by gentest_codegen.
// Do not edit manually.

#pragma once

#include <type_traits>

// This header is included while inside namespace gentest

)CPP";

inline constexpr std::string_view impl_preamble = R"CPP(// This file is auto-generated by gentest_codegen.
// Do not edit manually.

#pragma once

#include <utility>

namespace gentest {

)CPP";

inline constexpr std::string_view impl_footer = R"CPP(} // namespace gentest
)CPP";

} // namespace gentest::codegen::tpl::mocks
