if(NOT DEFINED PROG)
  message(FATAL_ERROR "CheckMeasuredCsvReport.cmake: PROG not set")
endif()

set(_emu)
if(DEFINED EMU)
  if(EMU MATCHES ";")
    set(_emu ${EMU})
  else()
    separate_arguments(_emu NATIVE_COMMAND "${EMU}")
  endif()
endif()

set(_args)
if(DEFINED ARGS)
  if(ARGS MATCHES ";")
    set(_args ${ARGS})
  else()
    separate_arguments(_args NATIVE_COMMAND "${ARGS}")
  endif()
endif()

set(_command ${_emu} "${PROG}" ${_args})
if(DEFINED ENV_VARS)
  set(_env)
  foreach(kv IN LISTS ENV_VARS)
    list(APPEND _env "${kv}")
  endforeach()
  set(_command ${CMAKE_COMMAND} -E env ${_env} ${_emu} "${PROG}" ${_args})
endif()

execute_process(
  COMMAND ${_command}
  RESULT_VARIABLE rc
  OUTPUT_VARIABLE out
  ERROR_VARIABLE err
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE)

if(DEFINED EXPECT_RC)
  if(NOT "${rc}" MATCHES "^-?[0-9]+$")
    message(FATAL_ERROR "Expected numeric exit code ${EXPECT_RC}, got '${rc}'. Stdout:\n${out}\nStderr:\n${err}")
  endif()
  if(NOT rc EQUAL EXPECT_RC)
    message(FATAL_ERROR "Expected exit code ${EXPECT_RC}, got ${rc}. Stdout:\n${out}\nStderr:\n${err}")
  endif()
endif()

string(REPLACE "\r\n" "\n" _out "${out}")

macro(_gentest_finish_csv_record)
  if(_csv_field_count EQUAL 1 AND NOT _csv_field_has_data)
    message(FATAL_ERROR "CSV report should not contain blank separator rows. Stdout:\n${out}")
  endif()
  if(NOT _csv_field_count EQUAL 6)
    message(FATAL_ERROR "Expected uniform six-column CSV row, got ${_csv_field_count} column(s). Stdout:\n${out}")
  endif()
  if(_csv_record_count EQUAL 0)
    if(NOT "${_csv_header}" STREQUAL "report,table,row,field,type,value")
      message(FATAL_ERROR "Unexpected CSV header '${_csv_header}'. Stdout:\n${out}")
    endif()
  endif()
  math(EXPR _csv_record_count "${_csv_record_count} + 1")
  set(_csv_field_count 1)
  set(_csv_field_has_data FALSE)
  set(_csv_header "")
endmacro()

string(LENGTH "${_out}" _csv_len)
if(_csv_len EQUAL 0)
  message(FATAL_ERROR "Expected CSV header and at least one data row. Stdout:\n${out}\nStderr:\n${err}")
endif()

set(_csv_record_count 0)
set(_csv_field_count 1)
set(_csv_field_has_data FALSE)
set(_csv_header "")
set(_csv_in_quote FALSE)
set(_csv_i 0)
while(_csv_i LESS _csv_len)
  string(SUBSTRING "${_out}" ${_csv_i} 1 _csv_ch)
  if(_csv_in_quote)
    if("${_csv_ch}" STREQUAL "\"")
      math(EXPR _csv_next_i "${_csv_i} + 1")
      set(_csv_next_ch "")
      if(_csv_next_i LESS _csv_len)
        string(SUBSTRING "${_out}" ${_csv_next_i} 1 _csv_next_ch)
      endif()
      if("${_csv_next_ch}" STREQUAL "\"")
        math(EXPR _csv_i "${_csv_i} + 1")
      else()
        set(_csv_in_quote FALSE)
      endif()
    endif()
    set(_csv_field_has_data TRUE)
  else()
    if("${_csv_ch}" STREQUAL "\"")
      if(_csv_field_has_data)
        message(FATAL_ERROR "Unexpected quote in unquoted CSV field. Stdout:\n${out}")
      endif()
      set(_csv_in_quote TRUE)
      set(_csv_field_has_data TRUE)
    elseif("${_csv_ch}" STREQUAL ",")
      math(EXPR _csv_field_count "${_csv_field_count} + 1")
      set(_csv_field_has_data FALSE)
    elseif("${_csv_ch}" STREQUAL "\n")
      _gentest_finish_csv_record()
    elseif("${_csv_ch}" STREQUAL "\r")
      # Ignore bare CR outside quoted fields.
    else()
      set(_csv_field_has_data TRUE)
    endif()
  endif()
  if(_csv_record_count EQUAL 0 AND NOT "${_csv_ch}" STREQUAL "\n")
    string(APPEND _csv_header "${_csv_ch}")
  endif()
  math(EXPR _csv_i "${_csv_i} + 1")
endwhile()

if(_csv_in_quote)
  message(FATAL_ERROR "CSV report ended inside a quoted field. Stdout:\n${out}")
endif()
if(_csv_field_count GREATER 1 OR _csv_field_has_data)
  _gentest_finish_csv_record()
endif()
if(_csv_record_count LESS 2)
  message(FATAL_ERROR "Expected CSV header and at least one data row. Stdout:\n${out}\nStderr:\n${err}")
endif()

if(DEFINED EXPECT_ISSUES_MIN)
  string(REGEX MATCHALL "(^|\n)measured,issues,[0-9]+,name,string," _issue_name_rows "${_out}")
  list(LENGTH _issue_name_rows _issue_count)
  if(_issue_count LESS EXPECT_ISSUES_MIN)
    message(FATAL_ERROR "Expected at least ${EXPECT_ISSUES_MIN} issue row(s), got ${_issue_count}. Stdout:\n${out}\nStderr:\n${err}")
  endif()
endif()

if(DEFINED REQUIRED_STDOUT_SUBSTRING AND NOT "${REQUIRED_STDOUT_SUBSTRING}" STREQUAL "")
  string(FIND "${out}" "${REQUIRED_STDOUT_SUBSTRING}" _required_stdout_pos)
  if(_required_stdout_pos EQUAL -1)
    message(FATAL_ERROR "Expected stdout substring not found: '${REQUIRED_STDOUT_SUBSTRING}'. Stdout:\n${out}")
  endif()
endif()

if(DEFINED FORBID_STDOUT_SUBSTRING AND NOT "${FORBID_STDOUT_SUBSTRING}" STREQUAL "")
  string(FIND "${out}" "${FORBID_STDOUT_SUBSTRING}" _forbid_stdout_pos)
  if(NOT _forbid_stdout_pos EQUAL -1)
    message(FATAL_ERROR "Forbidden stdout substring found: '${FORBID_STDOUT_SUBSTRING}'. Stdout:\n${out}")
  endif()
endif()

if(DEFINED REQUIRED_STDERR_SUBSTRING AND NOT "${REQUIRED_STDERR_SUBSTRING}" STREQUAL "")
  string(FIND "${err}" "${REQUIRED_STDERR_SUBSTRING}" _required_stderr_pos)
  if(_required_stderr_pos EQUAL -1)
    message(FATAL_ERROR "Expected stderr substring not found: '${REQUIRED_STDERR_SUBSTRING}'. Stderr:\n${err}\nStdout:\n${out}")
  endif()
endif()
