# Usage:
#   cmake -DPROG=<path> -DCASES=<n> [-DEXPECTED_LIST_FILE=<path>] [-DPASS=<n> -DFAIL=<n> -DSKIP=<n>] [-DXFAIL=<n>] [-DXPASS=<n>] [-DEXPECT_RC=<n>] -P tests/cmake/scripts/CheckTestInventory.cmake

if(NOT DEFINED PROG)
  message(FATAL_ERROR "PROG not set")
endif()

if(NOT DEFINED CASES)
  message(FATAL_ERROR "CASES not set")
endif()

set(_emu)
if(DEFINED EMU)
  if(EMU MATCHES ";")
    set(_emu ${EMU}) # already a list
  else()
    separate_arguments(_emu NATIVE_COMMAND "${EMU}") # string
  endif()
endif()

set(_args)
if(DEFINED ARGS)
  if(ARGS MATCHES ";")
    set(_args ${ARGS}) # already a list
  else()
    separate_arguments(_args NATIVE_COMMAND "${ARGS}") # string
  endif()
endif()

function(_gentest_count_output_lines text out_var)
  if("${text}" STREQUAL "")
    set(${out_var} 0 PARENT_SCOPE)
    return()
  endif()

  string(REGEX MATCHALL "\n" _lines "${text}")
  list(LENGTH _lines _line_count)
  if(NOT text MATCHES "\n$")
    math(EXPR _line_count "${_line_count} + 1")
  endif()
  set(${out_var} "${_line_count}" PARENT_SCOPE)
endfunction()

function(_gentest_normalize_text text out_var)
  string(ASCII 27 _esc)
  string(REPLACE "\r" "" _normalized "${text}")
  string(REGEX REPLACE "${_esc}\\[[0-9;:;?]*[A-Za-z]" "" _normalized "${_normalized}")
  string(REGEX REPLACE "\n+$" "" _normalized "${_normalized}")
  set(${out_var} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_gentest_normalize_sorted_lines text out_var)
  _gentest_normalize_text("${text}" _normalized)
  if("${_normalized}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  string(REPLACE "\n" ";" _lines "${_normalized}")
  set(_filtered)
  foreach(_line IN LISTS _lines)
    if(NOT _line STREQUAL "")
      list(APPEND _filtered "${_line}")
    endif()
  endforeach()
  list(SORT _filtered)
  set(${out_var} "${_filtered}" PARENT_SCOPE)
endfunction()

function(_gentest_count_status_lines text status out_var)
  set(_search_text "\n${text}")
  string(REGEX MATCHALL "\n[ \t]*\\[ ${status} \\]" _matches "${_search_text}")
  list(LENGTH _matches _count)
  set(${out_var} "${_count}" PARENT_SCOPE)
endfunction()

function(_gentest_run_and_capture name out_var err_var rc_var)
  execute_process(
    COMMAND ${_emu} "${PROG}" ${_args} ${ARGN}
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err
    RESULT_VARIABLE _rc)

  set(${out_var} "${_out}" PARENT_SCOPE)
  set(${err_var} "${_err}" PARENT_SCOPE)
  set(${rc_var} "${_rc}" PARENT_SCOPE)
endfunction()

function(_gentest_check_list_mode mode_name expected_cases)
  _gentest_run_and_capture("${mode_name}" _out _err _rc ${ARGN})
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "${mode_name} failed with code ${_rc}. Output:\n${_out}\nErrors:\n${_err}")
  endif()

  _gentest_count_output_lines("${_out}" _line_count)
  if(NOT _line_count EQUAL expected_cases)
    message(FATAL_ERROR "Expected ${expected_cases} ${mode_name} lines, got ${_line_count}. Output:\n${_out}")
  endif()
endfunction()

_gentest_check_list_mode("--list" "${CASES}" --list)
_gentest_check_list_mode("--list-tests" "${CASES}" --list-tests)

if(DEFINED EXPECTED_LIST_FILE AND NOT "${EXPECTED_LIST_FILE}" STREQUAL "")
  if(NOT EXISTS "${EXPECTED_LIST_FILE}")
    message(FATAL_ERROR "Expected list file not found: ${EXPECTED_LIST_FILE}")
  endif()
  _gentest_run_and_capture("--list-tests exact" _list_tests_out _list_tests_err _list_tests_rc --list-tests)
  if(NOT _list_tests_rc EQUAL 0)
    message(FATAL_ERROR "--list-tests exact failed with code ${_list_tests_rc}. Output:\n${_list_tests_out}\nErrors:\n${_list_tests_err}")
  endif()
  file(READ "${EXPECTED_LIST_FILE}" _expected_list_text)
  _gentest_normalize_sorted_lines("${_list_tests_out}" _normalized_actual_list)
  _gentest_normalize_sorted_lines("${_expected_list_text}" _normalized_expected_list)
  if(NOT _normalized_actual_list STREQUAL _normalized_expected_list)
    string(JOIN "\n" _expected_block ${_normalized_expected_list})
    string(JOIN "\n" _actual_block ${_normalized_actual_list})
    message(FATAL_ERROR
      "Expected --list-tests membership from ${EXPECTED_LIST_FILE}, but it differed.\nExpected:\n${_expected_block}\nActual:\n${_actual_block}")
  endif()
endif()

if(NOT DEFINED PASS AND NOT DEFINED FAIL AND NOT DEFINED SKIP)
  return()
endif()

if(NOT DEFINED PASS OR NOT DEFINED FAIL OR NOT DEFINED SKIP)
  message(FATAL_ERROR "PASS, FAIL, and SKIP must either all be set or all be omitted")
endif()

_gentest_run_and_capture("default run" out err rc)

_gentest_normalize_text("${out}${err}" all)
_gentest_count_status_lines("${all}" "PASS" pass_count)
_gentest_count_status_lines("${all}" "FAIL" fail_count)
_gentest_count_status_lines("${all}" "SKIP" skip_count)
_gentest_count_status_lines("${all}" "XFAIL" xfail_count)
_gentest_count_status_lines("${all}" "XPASS" xpass_count)

set(_ok TRUE)
if(NOT pass_count EQUAL PASS)
  message(STATUS "PASS count mismatch: expected ${PASS}, got ${pass_count}")
  set(_ok FALSE)
endif()
if(NOT fail_count EQUAL FAIL)
  message(STATUS "FAIL count mismatch: expected ${FAIL}, got ${fail_count}")
  set(_ok FALSE)
endif()
if(NOT skip_count EQUAL SKIP)
  message(STATUS "SKIP count mismatch: expected ${SKIP}, got ${skip_count}")
  set(_ok FALSE)
endif()
if(DEFINED XFAIL AND NOT "${XFAIL}" STREQUAL "" AND NOT xfail_count EQUAL XFAIL)
  message(STATUS "XFAIL count mismatch: expected ${XFAIL}, got ${xfail_count}")
  set(_ok FALSE)
endif()
if(DEFINED XPASS AND NOT "${XPASS}" STREQUAL "" AND NOT xpass_count EQUAL XPASS)
  message(STATUS "XPASS count mismatch: expected ${XPASS}, got ${xpass_count}")
  set(_ok FALSE)
endif()

if(DEFINED EXPECT_RC AND NOT "${EXPECT_RC}" STREQUAL "")
  if(NOT rc EQUAL EXPECT_RC)
    message(STATUS "Exit code mismatch: expected ${EXPECT_RC}, got ${rc}")
    set(_ok FALSE)
  endif()
else()
  set(_fail_like ${FAIL})
  if(DEFINED XPASS AND NOT "${XPASS}" STREQUAL "")
    math(EXPR _fail_like "${_fail_like} + ${XPASS}")
  endif()

  if(_fail_like GREATER 0)
    if(rc EQUAL 0)
      message(STATUS "Expected non-zero exit code when failures present, got ${rc}")
      set(_ok FALSE)
    endif()
  else()
    if(NOT rc EQUAL 0)
      message(STATUS "Unexpected non-zero exit code: ${rc}")
      set(_ok FALSE)
    endif()
  endif()
endif()

if(NOT _ok)
  message(FATAL_ERROR "Inventory check failed. Output:\n${out}\nErrors:\n${err}")
endif()
