set(GENTEST_SKIP_TEST_PREFIX "GENTEST_SKIP_TEST:")

function(gentest_skip_test reason)
  message(STATUS "${GENTEST_SKIP_TEST_PREFIX} ${reason}")
endfunction()

function(gentest_read_cache_value cache_file key out_found out_value)
  if(NOT EXISTS "${cache_file}")
    set(${out_found} FALSE PARENT_SCOPE)
    set(${out_value} "" PARENT_SCOPE)
    return()
  endif()

  file(STRINGS "${cache_file}" _cache_entry REGEX "^${key}:[^=]*=" LIMIT_COUNT 1)
  if(NOT _cache_entry)
    set(${out_found} FALSE PARENT_SCOPE)
    set(${out_value} "" PARENT_SCOPE)
    return()
  endif()

  list(GET _cache_entry 0 _cache_line)
  string(REGEX REPLACE "^${key}:[^=]*=" "" _cache_value "${_cache_line}")
  set(${out_found} TRUE PARENT_SCOPE)
  set(${out_value} "${_cache_value}" PARENT_SCOPE)
endfunction()

function(gentest_make_compact_fixture_work_dir out_var)
  set(one_value_args PREFIX SOURCE_DIR EXTRA_KEY)
  cmake_parse_arguments(MAKE "" "${one_value_args}" "" ${ARGN})

  if(NOT DEFINED BUILD_ROOT OR "${BUILD_ROOT}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compact_fixture_work_dir requires BUILD_ROOT to be set")
  endif()
  if(NOT DEFINED MAKE_PREFIX OR "${MAKE_PREFIX}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compact_fixture_work_dir requires PREFIX")
  endif()

  set(_hash_input "${MAKE_PREFIX}|${MAKE_SOURCE_DIR}|${MAKE_EXTRA_KEY}")
  string(MD5 _work_hash "${_hash_input}")
  string(SUBSTRING "${_work_hash}" 0 12 _work_suffix)
  set(${out_var} "${BUILD_ROOT}/${MAKE_PREFIX}_${_work_suffix}" PARENT_SCOPE)
endfunction()

function(gentest_make_compact_fixture_source_link out_var)
  set(one_value_args WORK_DIR SOURCE_DIR STEM)
  cmake_parse_arguments(MAKE "" "${one_value_args}" "" ${ARGN})

  if(NOT DEFINED MAKE_WORK_DIR OR "${MAKE_WORK_DIR}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compact_fixture_source_link requires WORK_DIR")
  endif()
  if(NOT DEFINED MAKE_SOURCE_DIR OR "${MAKE_SOURCE_DIR}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compact_fixture_source_link requires SOURCE_DIR")
  endif()
  if(NOT DEFINED MAKE_STEM OR "${MAKE_STEM}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compact_fixture_source_link requires STEM")
  endif()

  if(CMAKE_HOST_WIN32)
    file(TO_CMAKE_PATH "$ENV{SYSTEMDRIVE}" _gentest_system_drive)
    if(_gentest_system_drive STREQUAL "")
      file(TO_CMAKE_PATH "$ENV{USERPROFILE}" _gentest_system_drive)
    endif()
    if(_gentest_system_drive STREQUAL "")
      message(FATAL_ERROR "gentest_make_compact_fixture_source_link requires SYSTEMDRIVE or USERPROFILE on Windows")
    endif()
    string(MD5 _gentest_source_link_hash "${MAKE_SOURCE_DIR}|${MAKE_WORK_DIR}|${MAKE_STEM}")
    string(SUBSTRING "${_gentest_source_link_hash}" 0 12 _gentest_source_link_suffix)
    set(_gentest_source_link_root "${_gentest_system_drive}/gsrc")
    file(MAKE_DIRECTORY "${_gentest_source_link_root}")
    set(_link_path "${_gentest_source_link_root}/${MAKE_STEM}_${_gentest_source_link_suffix}")
    file(REMOVE_RECURSE "${_link_path}")
    set(_gentest_python_cmd "${Python3_EXECUTABLE}")
    if(_gentest_python_cmd STREQUAL "" OR NOT EXISTS "${_gentest_python_cmd}")
      find_program(_gentest_python_cmd NAMES python python3)
    endif()
    if(NOT _gentest_python_cmd)
      message(FATAL_ERROR "gentest_make_compact_fixture_source_link requires python or python3 on PATH for Windows source-view creation")
    endif()
    string(CONCAT _gentest_source_view_script
      "import pathlib, shutil, sys; "
      "src = pathlib.Path(sys.argv[1]); "
      "dst = pathlib.Path(sys.argv[2]); "
      "ignore = shutil.ignore_patterns('.git', 'build', 'build-*', 'gentest_scan_inspector_*', '.wt', '__pycache__'); "
      "shutil.copytree(src, dst, ignore=ignore)")
    execute_process(
      COMMAND "${_gentest_python_cmd}" -c "${_gentest_source_view_script}" "${MAKE_SOURCE_DIR}" "${_link_path}"
      RESULT_VARIABLE _link_rc
      OUTPUT_VARIABLE _link_out
      ERROR_VARIABLE _link_err
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_STRIP_TRAILING_WHITESPACE)
    if(NOT _link_rc EQUAL 0)
      message(FATAL_ERROR
        "gentest_make_compact_fixture_source_link failed to create the short Windows source view.\n"
        "source: ${MAKE_SOURCE_DIR}\n"
        "link: ${_link_path}\n"
        "stdout:\n${_link_out}\n"
        "stderr:\n${_link_err}")
    endif()
  else()
    set(_link_path "${MAKE_WORK_DIR}/${MAKE_STEM}")
    file(CREATE_LINK "${MAKE_SOURCE_DIR}" "${_link_path}" SYMBOLIC)
  endif()

  set(${out_var} "${_link_path}" PARENT_SCOPE)
endfunction()

function(gentest_cleanup_compact_fixture_source_link path)
  if("${path}" STREQUAL "")
    return()
  endif()

  file(TO_CMAKE_PATH "$ENV{SYSTEMDRIVE}" _gentest_system_drive)
  if(_gentest_system_drive STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{USERPROFILE}" _gentest_system_drive)
  endif()
  if(_gentest_system_drive STREQUAL "")
    return()
  endif()

  set(_gentest_source_link_root "${_gentest_system_drive}/gsrc")
  cmake_path(ABSOLUTE_PATH path NORMALIZE OUTPUT_VARIABLE _gentest_candidate_abs)
  cmake_path(ABSOLUTE_PATH _gentest_source_link_root NORMALIZE OUTPUT_VARIABLE _gentest_source_root_abs)
  string(TOLOWER "${_gentest_candidate_abs}" _gentest_candidate_cmp)
  string(TOLOWER "${_gentest_source_root_abs}" _gentest_source_root_cmp)
  string(FIND "${_gentest_candidate_cmp}/" "${_gentest_source_root_cmp}/" _gentest_prefix_pos)
  if(_gentest_prefix_pos EQUAL 0)
    file(REMOVE_RECURSE "${_gentest_candidate_abs}")
  endif()
endfunction()

function(gentest_remove_fixture_path path)
  if(NOT DEFINED BUILD_ROOT OR "${BUILD_ROOT}" STREQUAL "")
    message(FATAL_ERROR "gentest_remove_fixture_path requires BUILD_ROOT to be set")
  endif()
  if("${path}" STREQUAL "")
    message(FATAL_ERROR "gentest_remove_fixture_path requires a non-empty path")
  endif()

  set(_gentest_remove_candidate "${path}")
  set(_gentest_remove_build_root "${BUILD_ROOT}")
  cmake_path(ABSOLUTE_PATH _gentest_remove_candidate NORMALIZE OUTPUT_VARIABLE _gentest_remove_candidate_abs)
  cmake_path(ABSOLUTE_PATH _gentest_remove_build_root NORMALIZE OUTPUT_VARIABLE _gentest_remove_build_root_abs)

  string(TOLOWER "${_gentest_remove_candidate_abs}" _gentest_remove_candidate_abs_cmp)
  string(TOLOWER "${_gentest_remove_build_root_abs}" _gentest_remove_build_root_abs_cmp)

  if(_gentest_remove_candidate_abs_cmp STREQUAL _gentest_remove_build_root_abs_cmp)
    message(FATAL_ERROR
      "gentest_remove_fixture_path refuses to remove BUILD_ROOT directly: '${_gentest_remove_candidate_abs}'")
  endif()

  set(_gentest_remove_build_root_prefix "${_gentest_remove_build_root_abs_cmp}/")
  string(FIND "${_gentest_remove_candidate_abs_cmp}/" "${_gentest_remove_build_root_prefix}" _gentest_remove_prefix_pos)
  if(NOT _gentest_remove_prefix_pos EQUAL 0)
    message(FATAL_ERROR
      "gentest_remove_fixture_path refuses to remove a path outside BUILD_ROOT.\n"
      "BUILD_ROOT: ${_gentest_remove_build_root_abs}\n"
      "candidate: ${_gentest_remove_candidate_abs}")
  endif()

  file(REMOVE_RECURSE "${_gentest_remove_candidate_abs}")
endfunction()

function(_gentest_ninja_version program out_version)
  if(NOT EXISTS "${program}")
    set(${out_version} "" PARENT_SCOPE)
    return()
  endif()

  execute_process(
    COMMAND "${program}" --version
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE)

  if(NOT _rc EQUAL 0)
    set(${out_version} "" PARENT_SCOPE)
    return()
  endif()

  string(REGEX MATCH "[0-9]+\\.[0-9]+(\\.[0-9]+)?" _version "${_out}")
  set(${out_version} "${_version}" PARENT_SCOPE)
endfunction()

function(gentest_resolve_module_fixture_make_program out_program out_reason)
  if(DEFINED MAKE_PROGRAM AND NOT "${MAKE_PROGRAM}" STREQUAL "")
    _gentest_ninja_version("${MAKE_PROGRAM}" _make_program_version)
    get_filename_component(_make_program_name "${MAKE_PROGRAM}" NAME)
    set(_make_program_is_ninja FALSE)
    if(GENERATOR STREQUAL "Ninja" OR GENERATOR STREQUAL "Ninja Multi-Config" OR
       _make_program_name MATCHES "^ninja(|-build)(\\.exe)?$")
      set(_make_program_is_ninja TRUE)
    endif()
    if(_make_program_is_ninja)
      if(_make_program_version AND NOT _make_program_version VERSION_LESS 1.11)
        set(${out_program} "${MAKE_PROGRAM}" PARENT_SCOPE)
        set(${out_reason} "" PARENT_SCOPE)
        return()
      endif()
      if(_make_program_version)
        set(${out_reason} "configured CMAKE_MAKE_PROGRAM '${MAKE_PROGRAM}' is too old (${_make_program_version}); Ninja 1.11 or newer is required" PARENT_SCOPE)
      else()
        set(${out_reason} "configured CMAKE_MAKE_PROGRAM '${MAKE_PROGRAM}' is not executable or has no parseable Ninja version" PARENT_SCOPE)
      endif()
      set(${out_program} "" PARENT_SCOPE)
      return()
    endif()
  endif()

  find_program(_path_ninja NAMES ninja ninja-build)
  if(_path_ninja)
    _gentest_ninja_version("${_path_ninja}" _path_ninja_version)
    if(_path_ninja_version AND NOT _path_ninja_version VERSION_LESS 1.11)
      set(${out_program} "${_path_ninja}" PARENT_SCOPE)
      set(${out_reason} "" PARENT_SCOPE)
      return()
    endif()
    if(_path_ninja_version)
      set(${out_reason} "PATH ninja '${_path_ninja}' is too old (${_path_ninja_version}); Ninja 1.11 or newer is required" PARENT_SCOPE)
    else()
      set(${out_reason} "PATH ninja '${_path_ninja}' is not executable or has no parseable version" PARENT_SCOPE)
    endif()
  else()
    set(${out_reason} "no usable Ninja executable was found on PATH" PARENT_SCOPE)
  endif()
  set(${out_program} "" PARENT_SCOPE)
endfunction()

function(gentest_find_supported_ninja out_program out_reason)
  gentest_resolve_module_fixture_make_program(_resolved_make_program _resolved_reason)
  set(${out_program} "${_resolved_make_program}" PARENT_SCOPE)
  set(${out_reason} "${_resolved_reason}" PARENT_SCOPE)
endfunction()

function(gentest_detect_host_apple_sysroot out_var)
  set(_sysroot "")
  if(CMAKE_HOST_APPLE)
    set(_sysroot "$ENV{SDKROOT}")
    if("${_sysroot}" STREQUAL "")
      execute_process(
        COMMAND xcrun --sdk macosx --show-sdk-path
        RESULT_VARIABLE _xcrun_rc
        OUTPUT_VARIABLE _xcrun_out
        ERROR_VARIABLE _xcrun_err
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_STRIP_TRAILING_WHITESPACE)
      if(_xcrun_rc EQUAL 0 AND NOT "${_xcrun_out}" STREQUAL "")
        set(_sysroot "${_xcrun_out}")
      endif()
    endif()
  endif()
  set(${out_var} "${_sysroot}" PARENT_SCOPE)
endfunction()

function(gentest_append_host_apple_sysroot out_list_var)
  set(_args ${${out_list_var}})
  gentest_detect_host_apple_sysroot(_sysroot)
  if(NOT "${_sysroot}" STREQUAL "")
    list(APPEND _args "-DCMAKE_OSX_SYSROOT=${_sysroot}")
  endif()
  set(${out_list_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_append_host_apple_sysroot_compile_args out_list_var)
  set(_args ${${out_list_var}})
  gentest_detect_host_apple_sysroot(_sysroot)
  if(NOT "${_sysroot}" STREQUAL "")
    list(APPEND _args "-isysroot" "${_sysroot}")
  endif()
  set(${out_list_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_append_public_modules_cache_arg out_list_var)
  set(_args ${${out_list_var}})
  list(APPEND _args "-DGENTEST_ENABLE_PUBLIC_MODULES=ON")
  set(${out_list_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_is_clang_like out_var compiler_path)
  if("${compiler_path}" STREQUAL "")
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_compiler_name "${compiler_path}" NAME)
  if(_compiler_name MATCHES "^clang(\\+\\+)?([-.].*)?$")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(gentest_compiler_version_output out_var compiler_path)
  if("${compiler_path}" STREQUAL "" OR NOT EXISTS "${compiler_path}")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  execute_process(
    COMMAND "${compiler_path}" --version
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE)

  if(NOT _rc EQUAL 0)
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  set(${out_var} "${_out}\n${_err}" PARENT_SCOPE)
endfunction()

function(_gentest_is_known_compiler_launcher_name out_var tool_name)
  string(TOLOWER "${tool_name}" _tool_name_lower)
  if(_tool_name_lower STREQUAL "ccache"
     OR _tool_name_lower STREQUAL "sccache"
     OR _tool_name_lower STREQUAL "distcc"
     OR _tool_name_lower STREQUAL "icecc"
     OR _tool_name_lower STREQUAL "buildcache")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(gentest_compiler_path_is_launcher_wrapper out_var compiler_path)
  if("${compiler_path}" STREQUAL "" OR NOT EXISTS "${compiler_path}")
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  set(_is_wrapper FALSE)

  get_filename_component(_compiler_dir "${compiler_path}" DIRECTORY)
  get_filename_component(_compiler_dir_name "${_compiler_dir}" NAME)
  _gentest_is_known_compiler_launcher_name(_dir_is_launcher "${_compiler_dir_name}")
  if(_dir_is_launcher)
    set(_is_wrapper TRUE)
  endif()

  if(NOT _is_wrapper)
    get_filename_component(_compiler_realpath "${compiler_path}" REALPATH)
    if(NOT "${_compiler_realpath}" STREQUAL "")
      get_filename_component(_compiler_real_name "${_compiler_realpath}" NAME)
      string(REGEX REPLACE "\\.exe$" "" _compiler_real_name "${_compiler_real_name}")
      _gentest_is_known_compiler_launcher_name(_real_is_launcher "${_compiler_real_name}")
      if(_real_is_launcher)
        set(_is_wrapper TRUE)
      endif()
    endif()
  endif()

  set(${out_var} ${_is_wrapper} PARENT_SCOPE)
endfunction()

function(gentest_is_supported_module_fixture_clang out_var compiler_path)
  gentest_is_clang_like(_is_clang_like "${compiler_path}")
  if(NOT _is_clang_like)
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  gentest_compiler_version_output(_version_output "${compiler_path}")
  if(_version_output MATCHES "(^|[\\r\\n])Apple clang version ")
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  set(${out_var} TRUE PARENT_SCOPE)
endfunction()

function(gentest_module_cpp_source_textual_wrapper_skip_reason out_reason compiler_path)
  set(_reason "")

  if("${compiler_path}" STREQUAL "" OR NOT EXISTS "${compiler_path}")
    set(_reason "module .cpp source regression: no usable C++ compiler was provided")
  else()
    gentest_is_clang_like(_is_clang_like "${compiler_path}")
    gentest_compiler_version_output(_version_output "${compiler_path}")

    if(CMAKE_HOST_WIN32 AND _is_clang_like)
      set(_reason
        "module .cpp source regression: textual wrapper after public module import is not stable on Windows LLVM")
    elseif(_is_clang_like)
      if(_version_output MATCHES "(^|[\r\n])Apple clang version ")
        set(_reason "module .cpp source regression: Apple Clang module support is not covered by this fixture")
      elseif(_version_output MATCHES "clang version ([0-9]+)")
        set(_clang_major "${CMAKE_MATCH_1}")
        if(_clang_major VERSION_LESS 21)
          set(_reason
            "module .cpp source regression: textual wrapper after public module import requires Clang 21+; '${compiler_path}' reports Clang ${_clang_major}")
        endif()
      else()
        set(_reason
          "module .cpp source regression: unable to confirm Clang 21+ support for '${compiler_path}'")
      endif()
    elseif(_version_output MATCHES "(^|[\r\n])(g\\+\\+|c\\+\\+)[^\\r\\n]*\\) ([0-9]+)")
      set(_gcc_major "${CMAKE_MATCH_3}")
      if(_gcc_major VERSION_LESS 16)
        set(_reason
          "module .cpp source regression: textual wrapper after public module import is not stable on GNU C++ before GCC 16; '${compiler_path}' reports GCC ${_gcc_major}")
      endif()
    endif()
  endif()

  set(${out_reason} "${_reason}" PARENT_SCOPE)
endfunction()

function(_gentest_append_candidate_dir_unique list_var dir_path)
  if("${dir_path}" STREQUAL "" OR NOT EXISTS "${dir_path}" OR NOT IS_DIRECTORY "${dir_path}")
    set(${list_var} "${${list_var}}" PARENT_SCOPE)
    return()
  endif()

  set(_dirs ${${list_var}})
  list(APPEND _dirs "${dir_path}")
  list(REMOVE_DUPLICATES _dirs)
  set(${list_var} "${_dirs}" PARENT_SCOPE)
endfunction()

function(_gentest_append_toolchain_bin_dir_from_cmake_dir list_var cmake_dir_path)
  if("${cmake_dir_path}" STREQUAL "" OR NOT EXISTS "${cmake_dir_path}")
    set(${list_var} "${${list_var}}" PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_prefix "${cmake_dir_path}/../../.." ABSOLUTE)
  set(_dirs ${${list_var}})
  list(APPEND _dirs "${_prefix}/bin")
  list(REMOVE_DUPLICATES _dirs)
  set(${list_var} "${_dirs}" PARENT_SCOPE)
endfunction()

function(gentest_resolve_clang_fixture_compilers out_c out_cxx)
  set(_resolved_c "")
  set(_resolved_cxx "")

  gentest_is_supported_module_fixture_clang(_has_clang_c "${C_COMPILER}")
  gentest_compiler_path_is_launcher_wrapper(_c_is_launcher_wrapper "${C_COMPILER}")
  if(DEFINED C_COMPILER AND NOT "${C_COMPILER}" STREQUAL "" AND _has_clang_c AND NOT _c_is_launcher_wrapper)
    set(_resolved_c "${C_COMPILER}")
  endif()

  gentest_is_supported_module_fixture_clang(_has_clang_cxx "${CXX_COMPILER}")
  gentest_compiler_path_is_launcher_wrapper(_cxx_is_launcher_wrapper "${CXX_COMPILER}")
  if(DEFINED CXX_COMPILER AND NOT "${CXX_COMPILER}" STREQUAL "" AND _has_clang_cxx AND NOT _cxx_is_launcher_wrapper)
    set(_resolved_cxx "${CXX_COMPILER}")
  endif()

  if("${_resolved_c}" STREQUAL "" AND NOT "${_resolved_cxx}" STREQUAL "")
    get_filename_component(_clangxx_dir "${_resolved_cxx}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      set(_derived_c "${_clangxx_dir}/clang.exe")
    else()
      set(_derived_c "${_clangxx_dir}/clang")
    endif()
    if(EXISTS "${_derived_c}")
      set(_resolved_c "${_derived_c}")
    endif()
  endif()

  if("${_resolved_cxx}" STREQUAL "" AND NOT "${_resolved_c}" STREQUAL "")
    get_filename_component(_clang_dir "${_resolved_c}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      set(_derived_cxx "${_clang_dir}/clang++.exe")
    else()
      set(_derived_cxx "${_clang_dir}/clang++")
    endif()
    if(EXISTS "${_derived_cxx}")
      set(_resolved_cxx "${_derived_cxx}")
    endif()
  endif()

  set(_preferred_clang_dirs "")
  if(DEFINED CXX_COMPILER_CLANG_SCAN_DEPS AND NOT "${CXX_COMPILER_CLANG_SCAN_DEPS}" STREQUAL "")
    gentest_resolve_program_candidate(_resolved_scan_deps "${CXX_COMPILER_CLANG_SCAN_DEPS}")
    if(NOT "${_resolved_scan_deps}" STREQUAL "")
      get_filename_component(_scan_deps_dir "${_resolved_scan_deps}" DIRECTORY)
      _gentest_append_candidate_dir_unique(_preferred_clang_dirs "${_scan_deps_dir}")
    endif()
  endif()
  if(DEFINED LLVM_DIR AND NOT "${LLVM_DIR}" STREQUAL "")
    _gentest_append_toolchain_bin_dir_from_cmake_dir(_preferred_clang_dirs "${LLVM_DIR}")
  endif()
  if(DEFINED Clang_DIR AND NOT "${Clang_DIR}" STREQUAL "")
    _gentest_append_toolchain_bin_dir_from_cmake_dir(_preferred_clang_dirs "${Clang_DIR}")
  endif()

  if(CMAKE_HOST_WIN32)
    set(_clang_names clang.exe clang)
    set(_clangxx_names clang++.exe clang++)
    set(_versioned_clang_globs "clang-*.exe")
    set(_versioned_clangxx_globs "clang++-*.exe")
    set(_path_separator ";")
  else()
    set(_clang_names clang)
    set(_clangxx_names clang++)
    set(_versioned_clang_globs "clang-[0-9]*")
    set(_versioned_clangxx_globs "clang++-[0-9]*")
    set(_path_separator ":")
  endif()

  foreach(_preferred_dir IN LISTS _preferred_clang_dirs)
    if("${_resolved_c}" STREQUAL "")
      foreach(_candidate_name IN LISTS _clang_names)
        set(_candidate "${_preferred_dir}/${_candidate_name}")
        gentest_is_supported_module_fixture_clang(_candidate_ok "${_candidate}")
        if(_candidate_ok)
          set(_resolved_c "${_candidate}")
          break()
        endif()
      endforeach()
    endif()

    if("${_resolved_cxx}" STREQUAL "")
      foreach(_candidate_name IN LISTS _clangxx_names)
        set(_candidate "${_preferred_dir}/${_candidate_name}")
        gentest_is_supported_module_fixture_clang(_candidate_ok "${_candidate}")
        if(_candidate_ok)
          set(_resolved_cxx "${_candidate}")
          break()
        endif()
      endforeach()
    endif()

    if(NOT "${_resolved_c}" STREQUAL "" AND NOT "${_resolved_cxx}" STREQUAL "")
      break()
    endif()
  endforeach()

  if("${_resolved_c}" STREQUAL "")
    find_program(_found_clang NAMES ${_clang_names})
    gentest_is_supported_module_fixture_clang(_found_clang_ok "${_found_clang}")
    if(_found_clang_ok)
      set(_resolved_c "${_found_clang}")
    endif()
  endif()

  if("${_resolved_cxx}" STREQUAL "")
    find_program(_found_clangxx NAMES ${_clangxx_names})
    gentest_is_supported_module_fixture_clang(_found_clangxx_ok "${_found_clangxx}")
    if(_found_clangxx_ok)
      set(_resolved_cxx "${_found_clangxx}")
    endif()
  endif()

  if("${_resolved_c}" STREQUAL "" OR "${_resolved_cxx}" STREQUAL "")
    set(_path_entries "$ENV{PATH}")
    string(REPLACE "${_path_separator}" ";" _path_entries "${_path_entries}")
    list(REMOVE_DUPLICATES _path_entries)

    set(_versioned_clang_candidates "")
    set(_versioned_clangxx_candidates "")
    foreach(_path_entry IN LISTS _path_entries)
      if(NOT EXISTS "${_path_entry}" OR NOT IS_DIRECTORY "${_path_entry}")
        continue()
      endif()
      foreach(_pattern IN LISTS _versioned_clang_globs)
        file(GLOB _found_versioned_clang LIST_DIRECTORIES FALSE "${_path_entry}/${_pattern}")
        list(APPEND _versioned_clang_candidates ${_found_versioned_clang})
      endforeach()
      foreach(_pattern IN LISTS _versioned_clangxx_globs)
        file(GLOB _found_versioned_clangxx LIST_DIRECTORIES FALSE "${_path_entry}/${_pattern}")
        list(APPEND _versioned_clangxx_candidates ${_found_versioned_clangxx})
      endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _versioned_clang_candidates)
    list(REMOVE_DUPLICATES _versioned_clangxx_candidates)
    list(SORT _versioned_clang_candidates COMPARE NATURAL ORDER DESCENDING)
    list(SORT _versioned_clangxx_candidates COMPARE NATURAL ORDER DESCENDING)

    if("${_resolved_c}" STREQUAL "")
      foreach(_candidate IN LISTS _versioned_clang_candidates)
        gentest_is_supported_module_fixture_clang(_candidate_ok "${_candidate}")
        if(_candidate_ok)
          set(_resolved_c "${_candidate}")
          break()
        endif()
      endforeach()
    endif()
    if("${_resolved_cxx}" STREQUAL "")
      foreach(_candidate IN LISTS _versioned_clangxx_candidates)
        gentest_is_supported_module_fixture_clang(_candidate_ok "${_candidate}")
        if(_candidate_ok)
          set(_resolved_cxx "${_candidate}")
          break()
        endif()
      endforeach()
    endif()
  endif()

  set(${out_c} "${_resolved_c}" PARENT_SCOPE)
  set(${out_cxx} "${_resolved_cxx}" PARENT_SCOPE)
endfunction()

function(gentest_is_windows_native_llvm_clang out_is_windows_native_llvm_clang compiler_path)
  set(_is_windows_native_llvm_clang FALSE)
  if(CMAKE_HOST_WIN32 AND NOT "${compiler_path}" STREQUAL "")
    get_filename_component(_compiler_name_we "${compiler_path}" NAME_WE)
    string(TOLOWER "${_compiler_name_we}" _compiler_name_lower)
    if(_compiler_name_lower STREQUAL "clang-cl"
       OR _compiler_name_lower MATCHES "^clang(\\+\\+)?(-[0-9][0-9.]*)?$")
      set(_is_windows_native_llvm_clang TRUE)
    endif()
  endif()
  set(${out_is_windows_native_llvm_clang} "${_is_windows_native_llvm_clang}" PARENT_SCOPE)
endfunction()

function(gentest_is_windows_gnu_clang out_is_windows_gnu_clang compiler_path)
  set(_is_windows_gnu_clang FALSE)
  gentest_is_windows_native_llvm_clang(_is_windows_native_llvm_clang "${compiler_path}")
  if(_is_windows_native_llvm_clang)
    get_filename_component(_compiler_name_we "${compiler_path}" NAME_WE)
    string(TOLOWER "${_compiler_name_we}" _compiler_name_lower)
    if(NOT _compiler_name_lower STREQUAL "clang-cl")
      set(_is_windows_gnu_clang TRUE)
    endif()
  endif()
  set(${out_is_windows_gnu_clang} "${_is_windows_gnu_clang}" PARENT_SCOPE)
endfunction()

function(gentest_append_windows_native_llvm_cache_args out_var compiler_path)
  set(_args ${ARGN})
  gentest_is_windows_native_llvm_clang(_is_windows_native_llvm_clang "${compiler_path}")
  if(_is_windows_native_llvm_clang)
    list(APPEND _args
      "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>"
      "-DCMAKE_CXX_FLAGS_INIT=-D_ITERATOR_DEBUG_LEVEL=0 -D_HAS_ITERATOR_DEBUGGING=0")
  endif()
  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_append_windows_path_budget_cache_args out_var)
  set(_args ${${out_var}})
  if(CMAKE_HOST_WIN32)
    list(APPEND _args "-DCMAKE_OBJECT_PATH_MAX=128")
  endif()
  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_is_msvc_style_compiler out_var compiler_path)
  if("${compiler_path}" STREQUAL "")
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_compiler_name_we "${compiler_path}" NAME_WE)
  string(TOLOWER "${_compiler_name_we}" _compiler_name_lower)
  if(_compiler_name_lower STREQUAL "cl" OR _compiler_name_lower STREQUAL "clang-cl")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(gentest_normalize_std_flag_for_compiler out_var compiler_path std_flag)
  if("${std_flag}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  set(_normalized "${std_flag}")
  gentest_is_msvc_style_compiler(_msvc_style "${compiler_path}")
  if(_msvc_style)
    if(_normalized STREQUAL "-std=c++20")
      set(_normalized "/std:c++20")
    elseif(_normalized MATCHES "^-std=c\\+\\+(23|2b)$")
      set(_normalized "/std:c++latest")
    endif()
  else()
    if(_normalized STREQUAL "/std:c++20")
      set(_normalized "-std=c++20")
    elseif(_normalized STREQUAL "/std:c++latest")
      set(_normalized "-std=c++23")
    endif()
  endif()

  set(${out_var} "${_normalized}" PARENT_SCOPE)
endfunction()

function(gentest_normalize_include_args_for_compiler out_var compiler_path)
  set(_normalized_args)
  gentest_is_msvc_style_compiler(_msvc_style "${compiler_path}")
  foreach(_arg IN LISTS ARGN)
    set(_normalized_arg "${_arg}")
    if(_msvc_style)
      if(_arg MATCHES "^-I(.+)$")
        set(_normalized_arg "/I${CMAKE_MATCH_1}")
      endif()
    else()
      if(_arg MATCHES "^/I(.+)$")
        set(_normalized_arg "-I${CMAKE_MATCH_1}")
      endif()
    endif()
    list(APPEND _normalized_args "${_normalized_arg}")
  endforeach()
  set(${out_var} "${_normalized_args}" PARENT_SCOPE)
endfunction()

function(gentest_make_compile_only_command_args out_var)
  set(one_value_args COMPILER STD SOURCE OBJECT)
  set(multi_value_args INCLUDE_ARGS EXTRA_ARGS)
  cmake_parse_arguments(MAKE "" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(NOT DEFINED MAKE_COMPILER OR "${MAKE_COMPILER}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compile_only_command_args requires COMPILER")
  endif()
  if(NOT DEFINED MAKE_STD OR "${MAKE_STD}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compile_only_command_args requires STD")
  endif()
  if(NOT DEFINED MAKE_SOURCE OR "${MAKE_SOURCE}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compile_only_command_args requires SOURCE")
  endif()
  if(NOT DEFINED MAKE_OBJECT OR "${MAKE_OBJECT}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_compile_only_command_args requires OBJECT")
  endif()

  gentest_normalize_std_flag_for_compiler(_normalized_std "${MAKE_COMPILER}" "${MAKE_STD}")
  gentest_normalize_include_args_for_compiler(_normalized_include_args "${MAKE_COMPILER}" ${MAKE_INCLUDE_ARGS})

  set(_args "${MAKE_COMPILER}")
  if(NOT "${_normalized_std}" STREQUAL "")
    list(APPEND _args "${_normalized_std}")
  endif()
  list(APPEND _args ${_normalized_include_args})
  if(MAKE_EXTRA_ARGS)
    list(APPEND _args ${MAKE_EXTRA_ARGS})
  endif()

  gentest_is_msvc_style_compiler(_msvc_style "${MAKE_COMPILER}")
  if(_msvc_style)
    list(APPEND _args "/utf-8" "/EHsc" "/c" "${MAKE_SOURCE}" "/Fo${MAKE_OBJECT}")
  else()
    list(APPEND _args "-c" "${MAKE_SOURCE}" "-o" "${MAKE_OBJECT}")
  endif()

  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(_gentest_append_include_arg_unique list_var include_dir)
  if("${include_dir}" STREQUAL "" OR NOT EXISTS "${include_dir}" OR NOT IS_DIRECTORY "${include_dir}")
    set(${list_var} "${${list_var}}" PARENT_SCOPE)
    return()
  endif()

  file(TO_CMAKE_PATH "${include_dir}" _include_dir_norm)
  set(_args ${${list_var}})
  list(APPEND _args "-I${_include_dir_norm}")
  list(REMOVE_DUPLICATES _args)
  set(${list_var} "${_args}" PARENT_SCOPE)
endfunction()

function(_gentest_resolve_nearest_build_root out_var build_root)
  if("${build_root}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  file(TO_CMAKE_PATH "${build_root}" _root_norm)
  set(_current "${_root_norm}")
  set(_keep_searching ON)
  while(_keep_searching)
    if(EXISTS "${_current}/CMakeCache.txt")
      set(${out_var} "${_current}" PARENT_SCOPE)
      return()
    endif()

    get_filename_component(_parent "${_current}" DIRECTORY)
    if("${_parent}" STREQUAL "" OR "${_parent}" STREQUAL "${_current}")
      set(_keep_searching OFF)
    else()
      set(_current "${_parent}")
    endif()
  endwhile()

  set(${out_var} "${_root_norm}" PARENT_SCOPE)
endfunction()

function(gentest_append_public_dependency_include_args out_var)
  set(_args ${${out_var}})
  set(_build_root "${BUILD_ROOT}")
  if(ARGC GREATER 1 AND NOT "${ARGV1}" STREQUAL "")
    set(_build_root "${ARGV1}")
  endif()

  if("${_build_root}" STREQUAL "")
    message(FATAL_ERROR "gentest_append_public_dependency_include_args requires BUILD_ROOT or an explicit build root argument")
  endif()

  _gentest_resolve_nearest_build_root(_resolved_build_root "${_build_root}")
  _gentest_append_include_arg_unique(_args "${_resolved_build_root}/_deps/fmt-src/include")
  _gentest_append_include_arg_unique(_args "${_resolved_build_root}/_deps/fmt-build/include")

  file(GLOB _vcpkg_include_dirs LIST_DIRECTORIES TRUE "${_resolved_build_root}/vcpkg_installed/*/include")
  foreach(_include_dir IN LISTS _vcpkg_include_dirs)
    _gentest_append_include_arg_unique(_args "${_include_dir}")
  endforeach()
  unset(_include_dir)
  unset(_vcpkg_include_dirs)

  set(_cache_file "${_resolved_build_root}/CMakeCache.txt")
  if(EXISTS "${_cache_file}")
    file(STRINGS "${_cache_file}" _fmt_dir_line REGEX "^fmt_DIR:PATH=" LIMIT_COUNT 1)
    if(_fmt_dir_line)
      list(GET _fmt_dir_line 0 _fmt_dir_line_value)
      string(REGEX REPLACE "^fmt_DIR:PATH=" "" _fmt_dir "${_fmt_dir_line_value}")
      _gentest_append_include_arg_unique(_args "${_fmt_dir}/../fmt-src/include")
      _gentest_append_include_arg_unique(_args "${_fmt_dir}/../../fmt-src/include")
      _gentest_append_include_arg_unique(_args "${_fmt_dir}/../../../fmt-src/include")
      _gentest_append_include_arg_unique(_args "${_fmt_dir}/../../../../fmt-src/include")
      get_filename_component(_fmt_prefix "${_fmt_dir}/../../.." ABSOLUTE)
      _gentest_append_include_arg_unique(_args "${_fmt_prefix}/include")
      unset(_fmt_dir)
      unset(_fmt_dir_line_value)
      unset(_fmt_prefix)
    endif()
    unset(_fmt_dir_line)
  endif()
  unset(_cache_file)
  unset(_resolved_build_root)

  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_make_public_api_include_args out_var)
  set(options INCLUDE_TESTS APPLE_SYSROOT)
  set(one_value_args SOURCE_ROOT BUILD_ROOT)
  cmake_parse_arguments(MAKE "${options}" "${one_value_args}" "" ${ARGN})

  if(NOT DEFINED MAKE_SOURCE_ROOT OR "${MAKE_SOURCE_ROOT}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_public_api_include_args requires SOURCE_ROOT")
  endif()

  file(TO_CMAKE_PATH "${MAKE_SOURCE_ROOT}" _source_root_norm)
  set(_args "-I${_source_root_norm}/include")
  if(MAKE_INCLUDE_TESTS)
    list(APPEND _args "-I${_source_root_norm}/tests")
  endif()
  if(MAKE_APPLE_SYSROOT)
    gentest_append_host_apple_sysroot_compile_args(_args)
  endif()

  set(_build_root "${BUILD_ROOT}")
  if(DEFINED MAKE_BUILD_ROOT AND NOT "${MAKE_BUILD_ROOT}" STREQUAL "")
    set(_build_root "${MAKE_BUILD_ROOT}")
  endif()
  gentest_append_public_dependency_include_args(_args "${_build_root}")
  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_make_public_api_compile_args out_var)
  set(options INCLUDE_TESTS APPLE_SYSROOT)
  set(one_value_args COMPILER STD SOURCE_ROOT BUILD_ROOT)
  set(multi_value_args EXTRA_ARGS)
  cmake_parse_arguments(MAKE "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(NOT DEFINED MAKE_COMPILER OR "${MAKE_COMPILER}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_public_api_compile_args requires COMPILER")
  endif()
  if(NOT DEFINED MAKE_STD OR "${MAKE_STD}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_public_api_compile_args requires STD")
  endif()
  if(NOT DEFINED MAKE_SOURCE_ROOT OR "${MAKE_SOURCE_ROOT}" STREQUAL "")
    message(FATAL_ERROR "gentest_make_public_api_compile_args requires SOURCE_ROOT")
  endif()

  set(_args "${MAKE_COMPILER}" "${MAKE_STD}")
  set(_include_args_call
    SOURCE_ROOT "${MAKE_SOURCE_ROOT}"
    BUILD_ROOT "${MAKE_BUILD_ROOT}")
  if(MAKE_INCLUDE_TESTS)
    list(APPEND _include_args_call INCLUDE_TESTS)
  endif()
  if(MAKE_APPLE_SYSROOT)
    list(APPEND _include_args_call APPLE_SYSROOT)
  endif()
  gentest_make_public_api_include_args(_include_args ${_include_args_call})
  list(APPEND _args ${_include_args})
  if(MAKE_EXTRA_ARGS)
    list(APPEND _args ${MAKE_EXTRA_ARGS})
  endif()
  set(${out_var} "${_args}" PARENT_SCOPE)
endfunction()

function(gentest_assert_windows_native_llvm_cache_args build_dir compiler_path label)
  gentest_is_windows_native_llvm_clang(_is_windows_native_llvm_clang "${compiler_path}")
  if(NOT _is_windows_native_llvm_clang)
    return()
  endif()

  set(_cache_file "${build_dir}/CMakeCache.txt")
  if(NOT EXISTS "${_cache_file}")
    message(FATAL_ERROR
      "Expected ${label} build cache at '${_cache_file}' to validate Windows native LLVM compatibility args")
  endif()

  file(STRINGS "${_cache_file}" _runtime_entry REGEX "^CMAKE_MSVC_RUNTIME_LIBRARY:[^=]*=" LIMIT_COUNT 1)
  if(NOT _runtime_entry)
    message(FATAL_ERROR
      "Expected ${label} configure cache to contain CMAKE_MSVC_RUNTIME_LIBRARY for Windows native LLVM compatibility")
  endif()
  list(GET _runtime_entry 0 _runtime_line)
  string(FIND "${_runtime_line}" "MultiThreaded$<$<CONFIG:Debug>:Debug>" _runtime_pos)
  if(_runtime_pos EQUAL -1)
    message(FATAL_ERROR
      "Expected ${label} configure cache to keep the Windows native LLVM MSVC runtime setting, but saw '${_runtime_line}'")
  endif()

  file(STRINGS "${_cache_file}" _cxx_flags_entry REGEX "^CMAKE_CXX_FLAGS:[^=]*=" LIMIT_COUNT 1)
  if(NOT _cxx_flags_entry)
    message(FATAL_ERROR
      "Expected ${label} configure cache to contain CMAKE_CXX_FLAGS for Windows native LLVM compatibility")
  endif()
  list(GET _cxx_flags_entry 0 _cxx_flags_line)
  string(FIND "${_cxx_flags_line}" "_ITERATOR_DEBUG_LEVEL=0" _iter_debug_pos)
  string(FIND "${_cxx_flags_line}" "_HAS_ITERATOR_DEBUGGING=0" _has_iter_debug_pos)
  if(_iter_debug_pos EQUAL -1 OR _has_iter_debug_pos EQUAL -1)
    message(FATAL_ERROR
      "Expected ${label} configure cache to keep the Windows native LLVM iterator-debug compatibility flags, but saw '${_cxx_flags_line}'")
  endif()
endfunction()

function(gentest_resolve_fixture_build_type out_build_type compiler_path requested_build_type)
  set(_effective_build_type "${requested_build_type}")
  gentest_is_windows_gnu_clang(_is_windows_gnu_clang "${compiler_path}")
  if(_is_windows_gnu_clang)
    set(_effective_build_type "Release")
  endif()
  set(${out_build_type} "${_effective_build_type}" PARENT_SCOPE)
endfunction()

function(gentest_resolve_program_candidate out_program candidate)
  if("${candidate}" STREQUAL "")
    set(${out_program} "" PARENT_SCOPE)
    return()
  endif()

  if(EXISTS "${candidate}" AND NOT IS_DIRECTORY "${candidate}")
    set(${out_program} "${candidate}" PARENT_SCOPE)
    return()
  endif()

  set(_resolved "")
  get_filename_component(_candidate_name "${candidate}" NAME)
  if(NOT "${_candidate_name}" STREQUAL ""
     AND NOT IS_ABSOLUTE "${candidate}"
     AND NOT "${candidate}" MATCHES "[/\\\\]")
    unset(_resolved CACHE)
    unset(_resolved)
    find_program(_resolved NAMES "${candidate}" "${_candidate_name}" NO_CACHE)
  endif()

  if(_resolved)
    set(${out_program} "${_resolved}" PARENT_SCOPE)
    return()
  endif()

  set(${out_program} "" PARENT_SCOPE)
endfunction()

function(gentest_find_clang_scan_deps out_program compiler_path)
  set(_candidates)
  if(DEFINED CXX_COMPILER_CLANG_SCAN_DEPS AND NOT "${CXX_COMPILER_CLANG_SCAN_DEPS}" STREQUAL "")
    list(APPEND _candidates "${CXX_COMPILER_CLANG_SCAN_DEPS}")
  endif()
  if(NOT "${compiler_path}" STREQUAL "")
    get_filename_component(_compiler_dir "${compiler_path}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      list(APPEND _candidates "${_compiler_dir}/clang-scan-deps.exe")
      file(GLOB _versioned_scan_deps LIST_DIRECTORIES FALSE "${_compiler_dir}/clang-scan-deps-*.exe")
    else()
      list(APPEND _candidates "${_compiler_dir}/clang-scan-deps")
      file(GLOB _versioned_scan_deps LIST_DIRECTORIES FALSE "${_compiler_dir}/clang-scan-deps-*")
    endif()
    list(APPEND _candidates ${_versioned_scan_deps})
  endif()

  list(APPEND _candidates
    "clang-scan-deps"
    "clang-scan-deps-22"
    "clang-scan-deps-21"
    "clang-scan-deps-20"
    "clang-scan-deps-19")

  list(REMOVE_DUPLICATES _candidates)
  foreach(_candidate IN LISTS _candidates)
    gentest_resolve_program_candidate(_resolved_candidate "${_candidate}")
    if(NOT "${_resolved_candidate}" STREQUAL "")
      set(${out_program} "${_resolved_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_program} "" PARENT_SCOPE)
endfunction()
