if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "CheckQemuWorkflowPresets.cmake: SOURCE_DIR not set")
endif()

set(_presets_file "${SOURCE_DIR}/CMakePresets.json")
if(NOT EXISTS "${_presets_file}")
  message(FATAL_ERROR "Missing presets file: ${_presets_file}")
endif()

file(READ "${_presets_file}" _json)

function(_find_named_preset array_name preset_name out_index)
  string(JSON _len LENGTH "${_json}" ${array_name})
  set(_found -1)
  math(EXPR _last "${_len}-1")
  foreach(_i RANGE 0 ${_last})
    string(JSON _name GET "${_json}" ${array_name} ${_i} name)
    if(_name STREQUAL "${preset_name}")
      set(_found ${_i})
      break()
    endif()
  endforeach()
  set(${out_index} ${_found} PARENT_SCOPE)
endfunction()

function(_require_description array_name preset_name required_substring)
  _find_named_preset("${array_name}" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "${array_name} does not contain name='${preset_name}'")
  endif()

  string(JSON _description GET "${_json}" ${array_name} ${_preset_index} description)
  string(FIND "${_description}" "${required_substring}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR
      "${array_name} '${preset_name}' must document the host-codegen prerequisite with '${required_substring}'. "
      "Current description: ${_description}")
  endif()
endfunction()

function(_assert_workflow_steps workflow_name expected_configure expected_build expected_test)
  _find_named_preset("workflowPresets" "${workflow_name}" _workflow_index)
  if(_workflow_index EQUAL -1)
    message(FATAL_ERROR "workflowPresets does not contain name='${workflow_name}'")
  endif()

  string(JSON _steps_len LENGTH "${_json}" workflowPresets ${_workflow_index} steps)
  if("${expected_test}" STREQUAL "")
    if(NOT _steps_len EQUAL 2)
      message(FATAL_ERROR "Workflow '${workflow_name}' must contain exactly configure/build steps")
    endif()
  else()
    if(NOT _steps_len EQUAL 3)
      message(FATAL_ERROR "Workflow '${workflow_name}' must contain exactly configure/build/test steps")
    endif()
  endif()

  string(JSON _step0_type GET "${_json}" workflowPresets ${_workflow_index} steps 0 type)
  string(JSON _step0_name GET "${_json}" workflowPresets ${_workflow_index} steps 0 name)
  string(JSON _step1_type GET "${_json}" workflowPresets ${_workflow_index} steps 1 type)
  string(JSON _step1_name GET "${_json}" workflowPresets ${_workflow_index} steps 1 name)
  if(NOT _step0_type STREQUAL "configure" OR NOT _step0_name STREQUAL "${expected_configure}")
    message(FATAL_ERROR "Workflow '${workflow_name}' must configure preset '${expected_configure}'")
  endif()
  if(NOT _step1_type STREQUAL "build" OR NOT _step1_name STREQUAL "${expected_build}")
    message(FATAL_ERROR "Workflow '${workflow_name}' must build preset '${expected_build}'")
  endif()
  if(NOT "${expected_test}" STREQUAL "")
    string(JSON _step2_type GET "${_json}" workflowPresets ${_workflow_index} steps 2 type)
    string(JSON _step2_name GET "${_json}" workflowPresets ${_workflow_index} steps 2 name)
    if(NOT _step2_type STREQUAL "test" OR NOT _step2_name STREQUAL "${expected_test}")
      message(FATAL_ERROR "Workflow '${workflow_name}' must test preset '${expected_test}'")
    endif()
  endif()
endfunction()

function(_assert_configure_preset array_name preset_name expected_configure)
  _find_named_preset("${array_name}" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "${array_name} does not contain name='${preset_name}'")
  endif()

  string(JSON _configure_preset GET "${_json}" ${array_name} ${_preset_index} configurePreset)
  if(NOT _configure_preset STREQUAL "${expected_configure}")
    message(FATAL_ERROR
      "${array_name} preset '${preset_name}' must use configurePreset='${expected_configure}' (got '${_configure_preset}')")
  endif()
endfunction()

function(_assert_build_targets_contain preset_name)
  _find_named_preset("buildPresets" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "buildPresets does not contain name='${preset_name}'")
  endif()

  string(JSON _targets_len LENGTH "${_json}" buildPresets ${_preset_index} targets)
  if(_targets_len LESS 1)
    message(FATAL_ERROR "buildPresets '${preset_name}' must declare explicit targets")
  endif()

  set(_target_names "")
  math(EXPR _targets_last "${_targets_len}-1")
  foreach(_i RANGE 0 ${_targets_last})
    string(JSON _target_name GET "${_json}" buildPresets ${_preset_index} targets ${_i})
    list(APPEND _target_names "${_target_name}")
  endforeach()

  foreach(_required_target IN ITEMS gentest_unit_tests gentest_mocking_tests)
    list(FIND _target_names "${_required_target}" _required_target_index)
    if(_required_target_index EQUAL -1)
      message(FATAL_ERROR
        "buildPresets '${preset_name}' must build '${_required_target}' for the QEMU smoke slice")
    endif()
  endforeach()
endfunction()

function(_assert_test_filter_contains preset_name expected_regex)
  _find_named_preset("testPresets" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "testPresets does not contain name='${preset_name}'")
  endif()

  string(JSON _filter_name GET "${_json}" testPresets ${_preset_index} filter include name)
  if(NOT _filter_name STREQUAL "${expected_regex}")
    message(FATAL_ERROR
      "testPresets '${preset_name}' must use include.name='${expected_regex}' (got '${_filter_name}')")
  endif()
endfunction()

function(_assert_qemu_preset_bundle preset_root)
  _require_description(configurePresets "${preset_root}" "host-codegen workflow")
  _require_description(buildPresets "${preset_root}" "host-codegen workflow")
  _require_description(buildPresets "${preset_root}-full" "host-codegen workflow")
  _require_description(testPresets "${preset_root}" "host-codegen workflow")
  _require_description(testPresets "${preset_root}-full" "host-codegen workflow")
  _require_description(workflowPresets "${preset_root}" "host-codegen workflow")
  _require_description(workflowPresets "${preset_root}-full" "host-codegen workflow")

  _assert_workflow_steps("${preset_root}" "${preset_root}" "${preset_root}" "${preset_root}")
  _assert_workflow_steps("${preset_root}-full" "${preset_root}" "${preset_root}-full" "${preset_root}-full")
  _assert_configure_preset("buildPresets" "${preset_root}" "${preset_root}")
  _assert_configure_preset("buildPresets" "${preset_root}-full" "${preset_root}")
  _assert_configure_preset("testPresets" "${preset_root}" "${preset_root}")
  _assert_configure_preset("testPresets" "${preset_root}-full" "${preset_root}")
  _assert_build_targets_contain("${preset_root}")
  _assert_test_filter_contains("${preset_root}" "^(gentest_codegen_check_valid|unit|unit_inventory|mocking)$")
endfunction()

_assert_workflow_steps("host-codegen" "host-codegen" "host-codegen" "")
_assert_qemu_preset_bundle("aarch64-qemu")
_assert_qemu_preset_bundle("riscv64-qemu")
