if(NOT DEFINED PROG OR "${PROG}" STREQUAL "")
  message(FATAL_ERROR "CheckMemberOperatorTemplateKeywordBuild.cmake: PROG not set")
endif()
if(NOT DEFINED BUILD_ROOT OR "${BUILD_ROOT}" STREQUAL "")
  message(FATAL_ERROR "CheckMemberOperatorTemplateKeywordBuild.cmake: BUILD_ROOT not set")
endif()
if(NOT DEFINED GENTEST_SOURCE_DIR OR "${GENTEST_SOURCE_DIR}" STREQUAL "")
  message(FATAL_ERROR "CheckMemberOperatorTemplateKeywordBuild.cmake: GENTEST_SOURCE_DIR not set")
endif()
if(NOT DEFINED SOURCE_DIR OR "${SOURCE_DIR}" STREQUAL "")
  message(FATAL_ERROR "CheckMemberOperatorTemplateKeywordBuild.cmake: SOURCE_DIR not set")
endif()
if(NOT DEFINED TARGET_NAME OR "${TARGET_NAME}" STREQUAL "")
  message(FATAL_ERROR "CheckMemberOperatorTemplateKeywordBuild.cmake: TARGET_NAME not set")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/CheckModuleFixtureCommon.cmake")

if(DEFINED C_COMPILER AND NOT "${C_COMPILER}" STREQUAL "")
  set(_c_compiler "${C_COMPILER}")
else()
  set(_c_compiler "")
endif()
if(DEFINED CXX_COMPILER AND NOT "${CXX_COMPILER}" STREQUAL "")
  set(_cxx_compiler "${CXX_COMPILER}")
else()
  set(_cxx_compiler "")
endif()

if(UNIX)
  gentest_resolve_clang_fixture_compilers(_clang _clangxx)
  if(NOT "${_clang}" STREQUAL "" AND NOT "${_clangxx}" STREQUAL "")
    set(_c_compiler "${_clang}")
    set(_cxx_compiler "${_clangxx}")
  endif()
endif()

set(C_COMPILER "${_c_compiler}")
set(CXX_COMPILER "${_cxx_compiler}")
include("${CMAKE_CURRENT_LIST_DIR}/CheckCmakeFixtureBuild.cmake")
