# Requires:
#  -DPROG=<path to program>
# Optional:
#  -DEMU=<emulator command or list>
#  -DARGS=<program args as string or list>
#  -DEXPECT_RC=<expected exit code> (defaults to 0)
#  -DREQUIRED_SUBSTRING=<substring expected in stdout or FILE contents>
#  -DFILE=<path expected to be generated by the program>

if(NOT DEFINED PROG)
  message(FATAL_ERROR "CheckRunContract.cmake: PROG not set")
endif()

set(_emu)
if(DEFINED EMU)
  if(EMU MATCHES ";")
    set(_emu ${EMU}) # already a list
  else()
    separate_arguments(_emu NATIVE_COMMAND "${EMU}") # string
  endif()
endif()

set(_args)
if(DEFINED ARGS)
  if(ARGS MATCHES ";")
    set(_args ${ARGS}) # already a list
  else()
    separate_arguments(_args NATIVE_COMMAND "${ARGS}") # string
  endif()
endif()

if(DEFINED FILE)
  file(REMOVE "${FILE}")
endif()

execute_process(
  COMMAND ${_emu} "${PROG}" ${_args}
  OUTPUT_VARIABLE out
  ERROR_VARIABLE err
  RESULT_VARIABLE rc
)

if(DEFINED EXPECT_RC)
  if(NOT rc EQUAL EXPECT_RC)
    message(FATAL_ERROR "Expected exit code ${EXPECT_RC}, got ${rc}. Output:\n${out}\nErrors:\n${err}")
  endif()
else()
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Command failed with code ${rc}. Output:\n${out}\nErrors:\n${err}")
  endif()
endif()

set(_haystack "${out}")
set(_subject_label "output")
if(DEFINED FILE)
  if(NOT EXISTS "${FILE}")
    message(FATAL_ERROR "Expected file not found: ${FILE}")
  endif()
  file(READ "${FILE}" _haystack)
  set(_subject_label "file: ${FILE}")
endif()

if(DEFINED REQUIRED_SUBSTRING)
  string(FIND "${_haystack}" "${REQUIRED_SUBSTRING}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "Expected substring not found in ${_subject_label}: '${REQUIRED_SUBSTRING}'. Content:\n${_haystack}")
  endif()
endif()
