if(NOT DEFINED PROG OR PROG STREQUAL "")
  message(FATAL_ERROR "CheckJsonInventory.cmake requires -DPROG=<test executable>")
endif()

execute_process(
  COMMAND "${PROG}" --list-json
  RESULT_VARIABLE _result
  OUTPUT_VARIABLE _out
  ERROR_VARIABLE _err)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "--list-json failed with ${_result}.\nstdout:\n${_out}\nstderr:\n${_err}")
endif()
if(NOT _err STREQUAL "")
  message(FATAL_ERROR "--list-json wrote to stderr:\n${_err}")
endif()

string(JSON _case_count ERROR_VARIABLE _json_error LENGTH "${_out}")
if(_json_error OR _case_count LESS 1)
  message(FATAL_ERROR "--list-json did not return a non-empty JSON array: ${_json_error}\n${_out}")
endif()

set(_found FALSE)
math(EXPR _last_case "${_case_count} - 1")
foreach(_idx RANGE 0 ${_last_case})
  string(JSON _name GET "${_out}" ${_idx} name)
  if(NOT _name STREQUAL "integration/errors/errors/recover")
    continue()
  endif()

  set(_found TRUE)
  string(JSON _kind GET "${_out}" ${_idx} kind)
  string(JSON _owner GET "${_out}" ${_idx} owner)
  string(JSON _file GET "${_out}" ${_idx} file)
  string(JSON _line TYPE "${_out}" ${_idx} line)
  string(JSON _tags_count LENGTH "${_out}" ${_idx} tags)
  string(JSON _requires_count LENGTH "${_out}" ${_idx} requirements)
  string(JSON _skipped GET "${_out}" ${_idx} skipped)
  string(JSON _lifetime GET "${_out}" ${_idx} fixtureLifetime)

  if(NOT _kind STREQUAL "test" OR NOT _owner STREQUAL "team-runtime")
    message(FATAL_ERROR "Unexpected structured case metadata for integration/errors/errors/recover.\n${_out}")
  endif()
  if(_file STREQUAL "" OR NOT _line STREQUAL "NUMBER" OR _skipped OR NOT _lifetime STREQUAL "none")
    message(FATAL_ERROR "Invalid common inventory fields for integration/errors/errors/recover.\n${_out}")
  endif()

  set(_has_legacy_owner FALSE)
  if(_tags_count GREATER 0)
    math(EXPR _last_tag "${_tags_count} - 1")
    foreach(_tag_idx RANGE 0 ${_last_tag})
      string(JSON _tag GET "${_out}" ${_idx} tags ${_tag_idx})
      if(_tag STREQUAL "owner=team-runtime")
        set(_has_legacy_owner TRUE)
      endif()
    endforeach()
  endif()
  if(NOT _has_legacy_owner OR NOT _requires_count EQUAL 1)
    message(FATAL_ERROR "Expected owner compatibility tag and requirement array in JSON inventory.\n${_out}")
  endif()
endforeach()

if(NOT _found)
  message(FATAL_ERROR "Could not find integration/errors/errors/recover in JSON inventory.\n${_out}")
endif()
