if(NOT DEFINED PROG)
  message(FATAL_ERROR "CheckJunitAllureParity.cmake: PROG not set")
endif()
if(NOT DEFINED OUT_DIR)
  message(FATAL_ERROR "CheckJunitAllureParity.cmake: OUT_DIR not set")
endif()
if(NOT DEFINED JUNIT_PATH)
  message(FATAL_ERROR "CheckJunitAllureParity.cmake: JUNIT_PATH not set")
endif()
if(NOT DEFINED EXPECT_SUBSTRING)
  message(FATAL_ERROR "CheckJunitAllureParity.cmake: EXPECT_SUBSTRING not set")
endif()
if(NOT DEFINED EXPECT_CASE_NAME)
  message(FATAL_ERROR "CheckJunitAllureParity.cmake: EXPECT_CASE_NAME not set")
endif()
if(NOT DEFINED EXPECT_RC)
  set(EXPECT_RC 1)
endif()
if(NOT DEFINED PREPARE_JUNIT_AS_DIRECTORY)
  set(PREPARE_JUNIT_AS_DIRECTORY ON)
endif()

set(_emu)
if(DEFINED EMU)
  if(EMU MATCHES ";")
    set(_emu ${EMU})
  else()
    separate_arguments(_emu NATIVE_COMMAND "${EMU}")
  endif()
endif()

set(_args)
if(DEFINED ARGS)
  if(ARGS MATCHES ";")
    set(_args ${ARGS})
  else()
    separate_arguments(_args NATIVE_COMMAND "${ARGS}")
  endif()
endif()

file(REMOVE_RECURSE "${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")
if(PREPARE_JUNIT_AS_DIRECTORY)
  file(REMOVE_RECURSE "${JUNIT_PATH}")
  file(MAKE_DIRECTORY "${JUNIT_PATH}")
endif()

execute_process(
  COMMAND ${_emu} "${PROG}" ${_args} "--allure-dir=${OUT_DIR}" "--junit=${JUNIT_PATH}"
  RESULT_VARIABLE _rc
  OUTPUT_VARIABLE _out
  ERROR_VARIABLE _err
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE)

set(_all "${_out}\n${_err}")
if(NOT _rc EQUAL EXPECT_RC)
  message(FATAL_ERROR "Expected exit code ${EXPECT_RC}, got ${_rc}. Output:\n${_all}")
endif()

file(GLOB _result_files LIST_DIRECTORIES false "${OUT_DIR}/result-*-result.json")
if("${_result_files}" STREQUAL "")
  message(FATAL_ERROR "Expected Allure result files under ${OUT_DIR}. Output:\n${_all}")
endif()
if(DEFINED EXPECT_RESULT_COUNT AND NOT "${EXPECT_RESULT_COUNT}" STREQUAL "")
  list(LENGTH _result_files _result_count)
  if(NOT _result_count EQUAL EXPECT_RESULT_COUNT)
    message(FATAL_ERROR "Expected ${EXPECT_RESULT_COUNT} Allure result files, found ${_result_count}: ${_result_files}\n\nOutput:\n${_all}")
  endif()
endif()

set(_found 0)
set(_found_case 0)
foreach(_result_file IN LISTS _result_files)
  file(READ "${_result_file}" _content)
  string(FIND "${_content}" "${EXPECT_SUBSTRING}" _pos)
  if(NOT _pos EQUAL -1)
    set(_found 1)
  endif()
  string(FIND "${_content}" "${EXPECT_CASE_NAME}" _case_pos)
  if(NOT _case_pos EQUAL -1)
    set(_found_case 1)
  endif()
endforeach()

if(NOT _found)
  message(FATAL_ERROR "Expected Allure infra result to include '${EXPECT_SUBSTRING}'. Files:\n${_result_files}\n\nOutput:\n${_all}")
endif()
if(NOT _found_case)
  message(FATAL_ERROR "Expected Allure results to retain case '${EXPECT_CASE_NAME}'. Files:\n${_result_files}\n\nOutput:\n${_all}")
endif()
