#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib
import re
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate gentest non-CMake wrapper outputs and invoke gentest_codegen."
    )
    parser.add_argument(
        "--mode",
        choices=["suite", "mocks", "textual-mocks"],
        default="suite",
        help=(
            "Generation mode. `suite` emits test/codegen wrappers. `mocks` emits explicit mock surfaces. "
            "`textual-mocks` is a legacy alias for `--mode mocks --kind textual`."
        ),
    )
    parser.add_argument(
        "--kind",
        choices=["textual", "modules"],
        default="textual",
        help="Explicit source/surface kind. No auto-detection is performed.",
    )
    parser.add_argument(
        "--backend",
        choices=["generic", "meson", "xmake", "bazel"],
        default="generic",
        help="Optional backend label used for clearer diagnostics.",
    )
    parser.add_argument("--codegen", required=True, help="Path to gentest_codegen")
    parser.add_argument("--source-root", required=True, help="Project source root")
    parser.add_argument("--out-dir", required=True, help="Directory for generated shim/header outputs")
    parser.add_argument("--wrapper-output", required=True, help="Generated shim translation unit path")
    parser.add_argument("--header-output", required=True, help="Generated registration header path")
    parser.add_argument("--source-file", help="Original source file backing the shim")
    parser.add_argument("--defs-file", action="append", default=[], help="Explicit textual mock defs file")
    parser.add_argument("--include-root", action="append", default=[], help="Include roots used to rewrite local quoted includes in staged defs")
    parser.add_argument("--public-header", help="Generated public header for textual mock mode")
    parser.add_argument("--anchor-output", help="Generated anchor source for textual mock mode")
    parser.add_argument("--target-id", help="Stable identifier used for textual mock generated anchors")
    parser.add_argument("--depfile", default="", help="Optional depfile path to pass through to gentest_codegen")
    parser.add_argument("--compdb", default="", help="Optional compilation database directory")
    parser.add_argument("--mock-registry", default="", help="Generated mock registry header path")
    parser.add_argument("--mock-impl", default="", help="Generated mock implementation header path")
    parser.add_argument(
        "--clang-arg",
        action="append",
        default=[],
        help="Extra clang/gentest_codegen argument appended after `--`",
    )
    return parser.parse_args()


def normalize_mode_and_kind(args: argparse.Namespace) -> argparse.Namespace:
    if args.mode == "textual-mocks":
        if args.kind != "textual":
            raise SystemExit("`--mode textual-mocks` only supports `--kind textual`.")
        args.mode = "mocks"
    return args


def unsupported_modules_message(backend: str, mode: str) -> str:
    operation = "attach_codegen" if mode == "suite" else "add_mocks"
    if backend == "meson":
        return (
            "Meson "
            + operation
            + "(kind=modules) is intentionally unsupported for now because named-module "
            "dependency handling is not reliable enough in the current Meson/toolchain path. "
            "Use kind=textual for Meson, or use CMake for named modules."
        )
    return (
        "The shared non-CMake helper does not implement "
        + operation
        + "(kind=modules) yet."
    )


def resolve_input_path(path_arg: str, source_root: pathlib.Path) -> pathlib.Path:
    candidate = pathlib.Path(path_arg)
    if candidate.is_absolute():
        return candidate
    cwd_candidate = (pathlib.Path.cwd() / candidate).absolute()
    if cwd_candidate.exists():
        return cwd_candidate
    return (source_root / candidate).absolute()


def write_suite_shim(wrapper_output: pathlib.Path, source_file_for_include: pathlib.Path, header_output: pathlib.Path) -> None:
    header_name = header_output.name
    try:
        wrapper_include = pathlib.Path(os.path.relpath(source_file_for_include, wrapper_output.parent)).as_posix()
    except ValueError:
        wrapper_include = source_file_for_include.as_posix()
    content = f"""// This file is auto-generated by gentest (buildsystem shim).
// Do not edit manually.

// Include the original translation unit so fixture types and test bodies are
// visible for wrappers.
#include "{wrapper_include}"

// Include generated registrations after the original TU is visible.
// During codegen or dependency scans, this header may not exist yet.
#if !defined(GENTEST_CODEGEN) && __has_include("{header_name}")
#include "{header_name}"
#endif
"""
    wrapper_output.parent.mkdir(parents=True, exist_ok=True)
    wrapper_output.write_text(content, encoding="utf-8")


INCLUDE_PATTERN = re.compile(r'#[ \t]*include[ \t]*"([^"]+)"')


def resolve_stageable_include(
    include_path: str,
    source_file: pathlib.Path,
    source_root: pathlib.Path,
    include_roots: list[pathlib.Path],
) -> pathlib.Path | None:
    source_dir = source_file.parent
    normalized_root = source_root.absolute()
    normalized_include_roots = [root.absolute() for root in include_roots]
    if os.path.isabs(include_path):
        return None
    include_candidate = (source_dir / include_path).absolute()
    if not include_candidate.exists() or include_candidate.is_dir():
        return None
    for include_root in normalized_include_roots:
        try:
            include_candidate.relative_to(include_root)
            return include_candidate
        except ValueError:
            continue
    try:
        include_candidate.relative_to(normalized_root)
        return include_candidate
    except ValueError:
        return None


def stable_stage_dep_path(out_dir: pathlib.Path, source_file: pathlib.Path, source_root: pathlib.Path) -> pathlib.Path:
    try:
        stable_key = source_file.absolute().relative_to(source_root.absolute()).as_posix()
    except ValueError:
        stable_key = source_file.absolute().as_posix()
    digest = hashlib.md5(stable_key.encode("utf-8")).hexdigest()
    return out_dir / "deps" / f"{digest}_{source_file.name}"


def stage_textual_file(
    *,
    source_file: pathlib.Path,
    staged_path: pathlib.Path,
    source_root: pathlib.Path,
    include_roots: list[pathlib.Path],
    staged_files: dict[pathlib.Path, pathlib.Path],
) -> pathlib.Path:
    source_file = source_file.absolute()
    if source_file in staged_files:
        return staged_files[source_file]
    staged_files[source_file] = staged_path
    source_text = source_file.read_text(encoding="utf-8")

    def replace_include(match: re.Match[str]) -> str:
        include_path = match.group(1)
        include_candidate = resolve_stageable_include(include_path, source_file, source_root, include_roots)
        if include_candidate is None:
            return match.group(0)
        staged_dep = staged_files.get(include_candidate)
        if staged_dep is None:
            staged_dep = stable_stage_dep_path(
                staged_path.parent.parent if staged_path.parent.name == "deps" else staged_path.parent,
                include_candidate,
                source_root,
            )
            stage_textual_file(
                source_file=include_candidate,
                staged_path=staged_dep,
                source_root=source_root,
                include_roots=include_roots,
                staged_files=staged_files,
            )
        rewritten = pathlib.Path(os.path.relpath(staged_dep, staged_path.parent)).as_posix()
        return match.group(0).replace(f'"{include_path}"', f'"{rewritten}"')

    rewritten = INCLUDE_PATTERN.sub(replace_include, source_text)
    staged_path.parent.mkdir(parents=True, exist_ok=True)
    staged_path.write_text(rewritten if rewritten.endswith("\n") else rewritten + "\n", encoding="utf-8")
    return staged_path


def materialize_textual_mock_defs(
    out_dir: pathlib.Path,
    source_root: pathlib.Path,
    defs_files: list[pathlib.Path],
    include_roots: list[pathlib.Path],
) -> list[pathlib.Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    materialized: list[pathlib.Path] = []
    staged_files: dict[pathlib.Path, pathlib.Path] = {}
    for index, defs_file in enumerate(defs_files):
        staged_path = out_dir / f"def_{index:04d}_{defs_file.name}"
        materialized.append(
            stage_textual_file(
                source_file=defs_file,
                staged_path=staged_path,
                source_root=source_root,
                include_roots=include_roots,
                staged_files=staged_files,
            )
        )
    return materialized


def write_textual_mock_source(wrapper_output: pathlib.Path, defs_files_for_include: list[pathlib.Path], header_output: pathlib.Path) -> None:
    content = """// This file is auto-generated by gentest (buildsystem explicit mocks).
// Do not edit manually.

#include "gentest/mock.h"
"""
    for defs_file in defs_files_for_include:
        try:
            defs_include = pathlib.Path(os.path.relpath(defs_file, wrapper_output.parent)).as_posix()
        except ValueError:
            defs_include = defs_file.as_posix()
        content += f'#include "{defs_include}"\n'
    content += f"""
#if !defined(GENTEST_CODEGEN) && __has_include("{header_output.name}")
#include "{header_output.name}"
#endif
"""
    wrapper_output.parent.mkdir(parents=True, exist_ok=True)
    wrapper_output.write_text(content, encoding="utf-8")


def write_textual_mock_public_header(
    public_header: pathlib.Path,
    defs_files_for_include: list[pathlib.Path],
    mock_registry: pathlib.Path,
    mock_impl: pathlib.Path,
) -> None:
    content = """// This file is auto-generated by gentest (buildsystem explicit mocks).
// Do not edit manually.

#pragma once

#define GENTEST_NO_AUTO_MOCK_INCLUDE 1
#include "gentest/mock.h"
"""
    for defs_file in defs_files_for_include:
        try:
            defs_include = pathlib.Path(os.path.relpath(defs_file, public_header.parent)).as_posix()
        except ValueError:
            defs_include = defs_file.as_posix()
        content += f'#include "{defs_include}"\n'
    content += """#undef GENTEST_NO_AUTO_MOCK_INCLUDE

"""
    content += f'#include "{mock_registry.name}"\n'
    content += f'#include "{mock_impl.name}"\n'
    public_header.parent.mkdir(parents=True, exist_ok=True)
    public_header.write_text(content, encoding="utf-8")


def write_anchor_source(anchor_output: pathlib.Path, target_id: str) -> None:
    content = f"""// This file is auto-generated by gentest (buildsystem explicit mocks anchor).
// Do not edit manually.

namespace gentest::detail {{
int {target_id}_explicit_mock_anchor = 0;
}} // namespace gentest::detail
"""
    anchor_output.parent.mkdir(parents=True, exist_ok=True)
    anchor_output.write_text(content, encoding="utf-8")


def infer_compdb_dir(codegen_path: pathlib.Path) -> pathlib.Path | None:
    candidates = [codegen_path.parent, codegen_path.parent.parent]
    for candidate in candidates:
        if (candidate / "compile_commands.json").exists():
            return candidate
    return None


def resolve_compdb_dir(compdb_arg: str, codegen_path: pathlib.Path) -> pathlib.Path | None:
    if compdb_arg:
        return pathlib.Path(compdb_arg).resolve()
    return infer_compdb_dir(codegen_path)


def normalize_textual_mock_clang_args(
    clang_args: list[str],
    *,
    source_root: pathlib.Path,
    compdb_dir: pathlib.Path | None,
) -> list[str]:
    if compdb_dir is not None and compdb_dir == source_root:
        return list(clang_args)

    def normalize_path(path_text: str) -> str:
        if not path_text or os.path.isabs(path_text):
            return path_text
        if path_text.startswith("-") or path_text.startswith("@"):
            return path_text
        source_candidate = (source_root / path_text).resolve()
        if source_candidate.exists():
            return str(source_candidate)
        return path_text

    normalized: list[str] = []
    index = 0
    while index < len(clang_args):
        arg = clang_args[index]
        if arg in ("-I", "-isystem", "/I"):
            normalized.append(arg)
            if index + 1 < len(clang_args):
                normalized.append(normalize_path(clang_args[index + 1]))
                index += 2
                continue
            index += 1
            continue
        if arg.startswith("-I") and len(arg) > 2:
            normalized.append("-I" + normalize_path(arg[2:]))
            index += 1
            continue
        if arg.startswith("/I") and len(arg) > 2:
            normalized.append("/I" + normalize_path(arg[2:]))
            index += 1
            continue
        if arg.startswith("-isystem") and len(arg) > len("-isystem"):
            normalized.append("-isystem" + normalize_path(arg[len("-isystem") :]))
            index += 1
            continue
        normalized.append(arg)
        index += 1
    return normalized


def build_codegen_command(
    *,
    codegen_path: pathlib.Path,
    source_root: pathlib.Path,
    out_dir: pathlib.Path,
    header_output: pathlib.Path,
    scan_input: pathlib.Path,
    depfile: str,
    compdb_dir: pathlib.Path | None,
    clang_args: list[str],
    mock_registry: str,
    mock_impl: str,
    discover_mocks: bool,
) -> list[str]:
    command = [
        str(codegen_path),
        "--source-root",
        str(source_root),
        "--tu-out-dir",
        str(out_dir.resolve()),
        "--tu-header-output",
        str(header_output),
    ]
    if depfile:
        command.extend(["--depfile", str(pathlib.Path(depfile).resolve())])
    if compdb_dir:
        command.extend(["--compdb", str(compdb_dir)])
    if mock_registry:
        command.extend(["--mock-registry", str(pathlib.Path(mock_registry).resolve())])
    if mock_impl:
        command.extend(["--mock-impl", str(pathlib.Path(mock_impl).resolve())])
    if discover_mocks:
        command.append("--discover-mocks")
    command.append(str(scan_input))
    command.append("--")
    command.extend(clang_args)
    return command


def main() -> int:
    args = normalize_mode_and_kind(parse_args())

    source_root = pathlib.Path(args.source_root).resolve()
    wrapper_output = pathlib.Path(args.wrapper_output).resolve()
    header_output = pathlib.Path(args.header_output).resolve()
    out_dir = pathlib.Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    codegen_path = pathlib.Path(args.codegen).resolve()

    if args.kind == "modules":
        print(unsupported_modules_message(args.backend, args.mode), file=sys.stderr)
        return 1

    if args.mode == "suite":
        if not args.source_file:
            print("--source-file is required in suite mode", file=sys.stderr)
            return 1
        source_file = resolve_input_path(args.source_file, source_root)
        if not source_file.exists():
            print(f"source file does not exist: {source_file}", file=sys.stderr)
            return 1
        compdb_dir = resolve_compdb_dir(args.compdb, codegen_path)
        write_suite_shim(wrapper_output, source_file, header_output)
        command = build_codegen_command(
            codegen_path=codegen_path,
            source_root=source_root,
            out_dir=out_dir,
            header_output=header_output,
            scan_input=wrapper_output,
            depfile=args.depfile,
            compdb_dir=compdb_dir,
            clang_args=args.clang_arg,
            mock_registry=args.mock_registry,
            mock_impl=args.mock_impl,
            discover_mocks=False,
        )
        subprocess.run(command, check=True)
        return 0

    if not args.defs_file:
        print("--defs-file is required in mocks mode", file=sys.stderr)
        return 1
    if not args.public_header:
        print("--public-header is required in mocks mode", file=sys.stderr)
        return 1
    if not args.anchor_output:
        print("--anchor-output is required in mocks mode", file=sys.stderr)
        return 1
    if not args.target_id:
        print("--target-id is required in mocks mode", file=sys.stderr)
        return 1
    if not args.mock_registry or not args.mock_impl:
        print("--mock-registry and --mock-impl are required in mocks mode", file=sys.stderr)
        return 1

    defs_files: list[pathlib.Path] = []
    for defs_arg in args.defs_file:
        defs_file = resolve_input_path(defs_arg, source_root)
        if not defs_file.exists():
            print(f"defs file does not exist: {defs_file}", file=sys.stderr)
            return 1
        defs_files.append(defs_file)

    public_header = pathlib.Path(args.public_header).resolve()
    anchor_output = pathlib.Path(args.anchor_output).resolve()
    mock_registry = pathlib.Path(args.mock_registry).resolve()
    mock_impl = pathlib.Path(args.mock_impl).resolve()
    include_roots = [resolve_input_path(root_arg, source_root) for root_arg in args.include_root]
    compdb_dir = resolve_compdb_dir(args.compdb, codegen_path)
    normalized_clang_args = normalize_textual_mock_clang_args(
        args.clang_arg,
        source_root=source_root,
        compdb_dir=compdb_dir,
    )
    materialized_defs = materialize_textual_mock_defs(out_dir, source_root, defs_files, include_roots)
    write_textual_mock_source(wrapper_output, materialized_defs, header_output)
    write_textual_mock_public_header(public_header, materialized_defs, mock_registry, mock_impl)
    write_anchor_source(anchor_output, args.target_id)

    command = build_codegen_command(
        codegen_path=codegen_path,
        source_root=source_root,
        out_dir=out_dir,
        header_output=header_output,
        scan_input=wrapper_output,
        depfile=args.depfile,
        compdb_dir=compdb_dir,
        clang_args=normalized_clang_args,
        mock_registry=args.mock_registry,
        mock_impl=args.mock_impl,
        discover_mocks=True,
    )
    subprocess.run(command, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
