#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a classic per-TU gentest shim and invoke gentest_codegen for non-CMake buildsystems."
    )
    parser.add_argument("--codegen", required=True, help="Path to gentest_codegen")
    parser.add_argument("--source-root", required=True, help="Project source root")
    parser.add_argument("--out-dir", required=True, help="Directory for generated shim/header outputs")
    parser.add_argument("--wrapper-output", required=True, help="Generated shim translation unit path")
    parser.add_argument("--header-output", required=True, help="Generated registration header path")
    parser.add_argument("--source-file", required=True, help="Original source file backing the shim")
    parser.add_argument(
        "--wrapper-include",
        required=True,
        help="Quoted include path the shim should use for the original source (for example unit/cases.cpp)",
    )
    parser.add_argument("--compdb", default="", help="Optional compilation database directory")
    parser.add_argument(
        "--clang-arg",
        action="append",
        default=[],
        help="Extra clang/gentest_codegen argument appended after `--`",
    )
    return parser.parse_args()


def write_shim(wrapper_output: pathlib.Path, wrapper_include: str, header_output: pathlib.Path) -> None:
    header_name = header_output.name
    content = f"""// This file is auto-generated by gentest (buildsystem shim).
// Do not edit manually.

// Include the original translation unit so fixture types and test bodies are
// visible for wrappers.
#include "{wrapper_include}"

// Include generated registrations after the original TU is visible.
// During codegen or dependency scans, this header may not exist yet.
#if !defined(GENTEST_CODEGEN) && __has_include("{header_name}")
#include "{header_name}"
#endif
"""
    wrapper_output.parent.mkdir(parents=True, exist_ok=True)
    wrapper_output.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()

    source_root = pathlib.Path(args.source_root).resolve()
    source_file = pathlib.Path(args.source_file).resolve()
    if not source_file.exists():
        print(f"source file does not exist: {source_file}", file=sys.stderr)
        return 1

    wrapper_output = pathlib.Path(args.wrapper_output).resolve()
    header_output = pathlib.Path(args.header_output).resolve()
    pathlib.Path(args.out_dir).mkdir(parents=True, exist_ok=True)

    write_shim(wrapper_output, args.wrapper_include, header_output)

    command = [
        str(pathlib.Path(args.codegen).resolve()),
        "--source-root",
        str(source_root),
        "--tu-out-dir",
        str(pathlib.Path(args.out_dir).resolve()),
        "--tu-header-output",
        str(header_output),
    ]
    if args.compdb:
        command.extend(["--compdb", str(pathlib.Path(args.compdb).resolve())])
    command.append(str(wrapper_output))
    command.append("--")
    command.extend(args.clang_arg)

    subprocess.run(command, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
