#pragma once

#if defined(GENTEST_MOCK_REGISTRY_PATH) && !defined(GENTEST_CODEGEN)
#ifndef GENTEST_DETAIL_MOCK_STRINGIFY_IMPL
#define GENTEST_DETAIL_MOCK_STRINGIFY_IMPL(x) #x
#define GENTEST_DETAIL_MOCK_STRINGIFY(x)      GENTEST_DETAIL_MOCK_STRINGIFY_IMPL(x)
#endif
#define GENTEST_MOCK_REGISTRY_HEADER GENTEST_DETAIL_MOCK_STRINGIFY(GENTEST_MOCK_REGISTRY_PATH)
#if __has_include(GENTEST_MOCK_REGISTRY_HEADER)
#include GENTEST_MOCK_REGISTRY_HEADER
#endif
#undef GENTEST_MOCK_REGISTRY_HEADER
#endif

#if defined(GENTEST_DETAIL_MOCK_STRINGIFY)
#undef GENTEST_DETAIL_MOCK_STRINGIFY
#endif
#if defined(GENTEST_DETAIL_MOCK_STRINGIFY_IMPL)
#undef GENTEST_DETAIL_MOCK_STRINGIFY_IMPL
#endif
