set(GENTEST_SKIP_TEST_PREFIX "GENTEST_SKIP_TEST:")

function(gentest_skip_test reason)
  message(STATUS "${GENTEST_SKIP_TEST_PREFIX} ${reason}")
endfunction()

function(_gentest_ninja_version program out_version)
  if(NOT EXISTS "${program}")
    set(${out_version} "" PARENT_SCOPE)
    return()
  endif()

  execute_process(
    COMMAND "${program}" --version
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE)

  if(NOT _rc EQUAL 0)
    set(${out_version} "" PARENT_SCOPE)
    return()
  endif()

  string(REGEX MATCH "[0-9]+\\.[0-9]+(\\.[0-9]+)?" _version "${_out}")
  set(${out_version} "${_version}" PARENT_SCOPE)
endfunction()

function(gentest_resolve_module_fixture_make_program out_program out_reason)
  if(NOT DEFINED GENERATOR OR (NOT GENERATOR STREQUAL "Ninja" AND NOT GENERATOR STREQUAL "Ninja Multi-Config"))
    if(DEFINED MAKE_PROGRAM AND NOT "${MAKE_PROGRAM}" STREQUAL "")
      set(${out_program} "${MAKE_PROGRAM}" PARENT_SCOPE)
    else()
      set(${out_program} "" PARENT_SCOPE)
    endif()
    set(${out_reason} "" PARENT_SCOPE)
    return()
  endif()

  set(_candidates)
  if(DEFINED MAKE_PROGRAM AND NOT "${MAKE_PROGRAM}" STREQUAL "")
    _gentest_ninja_version("${MAKE_PROGRAM}" _make_program_version)
    if(_make_program_version AND NOT _make_program_version VERSION_LESS 1.11)
      set(${out_program} "${MAKE_PROGRAM}" PARENT_SCOPE)
      set(${out_reason} "" PARENT_SCOPE)
      return()
    endif()
    if(_make_program_version)
      set(${out_reason} "configured CMAKE_MAKE_PROGRAM '${MAKE_PROGRAM}' is too old (${_make_program_version}); Ninja 1.11 or newer is required" PARENT_SCOPE)
    else()
      set(${out_reason} "configured CMAKE_MAKE_PROGRAM '${MAKE_PROGRAM}' is not executable or has no parseable version" PARENT_SCOPE)
    endif()
    set(${out_program} "" PARENT_SCOPE)
    return()
  endif()

  find_program(_path_ninja NAMES ninja ninja-build)
  if(_path_ninja)
    _gentest_ninja_version("${_path_ninja}" _path_ninja_version)
    if(_path_ninja_version AND NOT _path_ninja_version VERSION_LESS 1.11)
      set(${out_program} "${_path_ninja}" PARENT_SCOPE)
      set(${out_reason} "" PARENT_SCOPE)
      return()
    endif()
    if(_path_ninja_version)
      set(${out_reason} "PATH ninja '${_path_ninja}' is too old (${_path_ninja_version}); Ninja 1.11 or newer is required" PARENT_SCOPE)
    else()
      set(${out_reason} "PATH ninja '${_path_ninja}' is not executable or has no parseable version" PARENT_SCOPE)
    endif()
  else()
    set(${out_reason} "no usable Ninja executable was found on PATH" PARENT_SCOPE)
  endif()
  set(${out_program} "" PARENT_SCOPE)
endfunction()

function(gentest_find_supported_ninja out_program out_reason)
  gentest_resolve_module_fixture_make_program(_resolved_make_program _resolved_reason)
  set(${out_program} "${_resolved_make_program}" PARENT_SCOPE)
  set(${out_reason} "${_resolved_reason}" PARENT_SCOPE)
endfunction()

function(gentest_is_clang_like out_var compiler_path)
  if("${compiler_path}" STREQUAL "")
    set(${out_var} FALSE PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_compiler_name "${compiler_path}" NAME)
  if(_compiler_name MATCHES "^clang(\\+\\+)?([-.].*)?$")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(gentest_resolve_clang_fixture_compilers out_c out_cxx)
  set(_resolved_c "")
  set(_resolved_cxx "")

  gentest_is_clang_like(_has_clang_c "${C_COMPILER}")
  if(DEFINED C_COMPILER AND NOT "${C_COMPILER}" STREQUAL "" AND _has_clang_c)
    set(_resolved_c "${C_COMPILER}")
  endif()

  gentest_is_clang_like(_has_clang_cxx "${CXX_COMPILER}")
  if(DEFINED CXX_COMPILER AND NOT "${CXX_COMPILER}" STREQUAL "" AND _has_clang_cxx)
    set(_resolved_cxx "${CXX_COMPILER}")
  endif()

  if("${_resolved_c}" STREQUAL "" AND NOT "${_resolved_cxx}" STREQUAL "")
    get_filename_component(_clangxx_dir "${_resolved_cxx}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      set(_derived_c "${_clangxx_dir}/clang.exe")
    else()
      set(_derived_c "${_clangxx_dir}/clang")
    endif()
    if(EXISTS "${_derived_c}")
      set(_resolved_c "${_derived_c}")
    endif()
  endif()

  if("${_resolved_cxx}" STREQUAL "" AND NOT "${_resolved_c}" STREQUAL "")
    get_filename_component(_clang_dir "${_resolved_c}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      set(_derived_cxx "${_clang_dir}/clang++.exe")
    else()
      set(_derived_cxx "${_clang_dir}/clang++")
    endif()
    if(EXISTS "${_derived_cxx}")
      set(_resolved_cxx "${_derived_cxx}")
    endif()
  endif()

  if(CMAKE_HOST_WIN32)
    set(_clang_names clang.exe clang)
    set(_clangxx_names clang++.exe clang++)
    set(_versioned_clang_globs "clang-*.exe")
    set(_versioned_clangxx_globs "clang++-*.exe")
    set(_path_separator ";")
  else()
    set(_clang_names clang)
    set(_clangxx_names clang++)
    set(_versioned_clang_globs "clang-[0-9]*")
    set(_versioned_clangxx_globs "clang++-[0-9]*")
    set(_path_separator ":")
  endif()

  if("${_resolved_c}" STREQUAL "")
    find_program(_found_clang NAMES ${_clang_names})
    if(_found_clang)
      set(_resolved_c "${_found_clang}")
    endif()
  endif()

  if("${_resolved_cxx}" STREQUAL "")
    find_program(_found_clangxx NAMES ${_clangxx_names})
    if(_found_clangxx)
      set(_resolved_cxx "${_found_clangxx}")
    endif()
  endif()

  if("${_resolved_c}" STREQUAL "" OR "${_resolved_cxx}" STREQUAL "")
    set(_path_entries "$ENV{PATH}")
    string(REPLACE "${_path_separator}" ";" _path_entries "${_path_entries}")
    list(REMOVE_DUPLICATES _path_entries)

    set(_versioned_clang_candidates "")
    set(_versioned_clangxx_candidates "")
    foreach(_path_entry IN LISTS _path_entries)
      if(NOT EXISTS "${_path_entry}" OR NOT IS_DIRECTORY "${_path_entry}")
        continue()
      endif()
      foreach(_pattern IN LISTS _versioned_clang_globs)
        file(GLOB _found_versioned_clang LIST_DIRECTORIES FALSE "${_path_entry}/${_pattern}")
        list(APPEND _versioned_clang_candidates ${_found_versioned_clang})
      endforeach()
      foreach(_pattern IN LISTS _versioned_clangxx_globs)
        file(GLOB _found_versioned_clangxx LIST_DIRECTORIES FALSE "${_path_entry}/${_pattern}")
        list(APPEND _versioned_clangxx_candidates ${_found_versioned_clangxx})
      endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _versioned_clang_candidates)
    list(REMOVE_DUPLICATES _versioned_clangxx_candidates)
    list(SORT _versioned_clang_candidates COMPARE NATURAL ORDER DESCENDING)
    list(SORT _versioned_clangxx_candidates COMPARE NATURAL ORDER DESCENDING)

    if("${_resolved_c}" STREQUAL "" AND _versioned_clang_candidates)
      list(GET _versioned_clang_candidates 0 _resolved_c)
    endif()
    if("${_resolved_cxx}" STREQUAL "" AND _versioned_clangxx_candidates)
      list(GET _versioned_clangxx_candidates 0 _resolved_cxx)
    endif()
  endif()

  set(${out_c} "${_resolved_c}" PARENT_SCOPE)
  set(${out_cxx} "${_resolved_cxx}" PARENT_SCOPE)
endfunction()

function(gentest_find_clang_scan_deps out_program compiler_path)
  set(_candidates)
  if(DEFINED CXX_COMPILER_CLANG_SCAN_DEPS AND NOT "${CXX_COMPILER_CLANG_SCAN_DEPS}" STREQUAL "")
    list(APPEND _candidates "${CXX_COMPILER_CLANG_SCAN_DEPS}")
  endif()
  if(NOT "${compiler_path}" STREQUAL "")
    get_filename_component(_compiler_dir "${compiler_path}" DIRECTORY)
    if(CMAKE_HOST_WIN32)
      list(APPEND _candidates "${_compiler_dir}/clang-scan-deps.exe")
      file(GLOB _versioned_scan_deps LIST_DIRECTORIES FALSE "${_compiler_dir}/clang-scan-deps-*.exe")
    else()
      list(APPEND _candidates "${_compiler_dir}/clang-scan-deps")
      file(GLOB _versioned_scan_deps LIST_DIRECTORIES FALSE "${_compiler_dir}/clang-scan-deps-*")
    endif()
    list(APPEND _candidates ${_versioned_scan_deps})
  endif()

  find_program(_scan_deps NAMES clang-scan-deps clang-scan-deps-22 clang-scan-deps-21 clang-scan-deps-20 clang-scan-deps-19)
  if(_scan_deps)
    list(APPEND _candidates "${_scan_deps}")
  endif()

  list(REMOVE_DUPLICATES _candidates)
  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      set(${out_program} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_program} "" PARENT_SCOPE)
endfunction()
