if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "CheckDiagnosticWorkflowLanes.cmake: SOURCE_DIR not set")
endif()

set(_presets_file "${SOURCE_DIR}/CMakePresets.json")
if(NOT EXISTS "${_presets_file}")
  message(FATAL_ERROR "Missing presets file: ${_presets_file}")
endif()

set(_workflow_file "${SOURCE_DIR}/.github/workflows/cmake.yml")
if(NOT EXISTS "${_workflow_file}")
  message(FATAL_ERROR "Missing workflow file: ${_workflow_file}")
endif()

file(READ "${_presets_file}" _json)
file(READ "${_workflow_file}" _workflow_content)

function(_find_named_preset array_name preset_name out_index)
  string(JSON _len LENGTH "${_json}" ${array_name})
  if(_len LESS 1)
    message(FATAL_ERROR "No ${array_name} found in ${_presets_file}")
  endif()

  set(_found -1)
  math(EXPR _last "${_len}-1")
  foreach(_i RANGE 0 ${_last})
    string(JSON _name GET "${_json}" ${array_name} ${_i} name)
    if(_name STREQUAL "${preset_name}")
      set(_found ${_i})
      break()
    endif()
  endforeach()

  set(${out_index} ${_found} PARENT_SCOPE)
endfunction()

function(_get_json_string out_var)
  set(options OPTIONAL)
  set(one_value_args "")
  set(multi_value_args PATH)
  cmake_parse_arguments(GET "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  string(JSON _value ERROR_VARIABLE _error GET "${_json}" ${GET_PATH})
  if(NOT _error STREQUAL "NOTFOUND")
    if(GET_OPTIONAL)
      set(${out_var} "" PARENT_SCOPE)
      return()
    endif()
    message(FATAL_ERROR "Missing JSON path '${GET_PATH}' in ${_presets_file}: ${_error}")
  endif()
  set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_require_preset array_name preset_name)
  _find_named_preset("${array_name}" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "${array_name} does not contain name='${preset_name}'")
  endif()
endfunction()

function(_assert_configure_preset array_name preset_name expected_configure)
  _find_named_preset("${array_name}" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "${array_name} does not contain name='${preset_name}'")
  endif()

  _get_json_string(_configure_preset PATH ${array_name} ${_preset_index} configurePreset)
  if(NOT _configure_preset STREQUAL "${expected_configure}")
    message(FATAL_ERROR
      "${array_name} preset '${preset_name}' must use configurePreset='${expected_configure}' (got '${_configure_preset}')")
  endif()
endfunction()

function(_assert_workflow_steps workflow_name expected_configure expected_build expected_test)
  _find_named_preset("workflowPresets" "${workflow_name}" _workflow_index)
  if(_workflow_index EQUAL -1)
    message(FATAL_ERROR "workflowPresets does not contain name='${workflow_name}'")
  endif()

  string(JSON _steps_len LENGTH "${_json}" workflowPresets ${_workflow_index} steps)
  if(NOT _steps_len EQUAL 3)
    message(FATAL_ERROR "Workflow '${workflow_name}' must contain exactly configure/build/test steps")
  endif()

  _get_json_string(_step0_type PATH workflowPresets ${_workflow_index} steps 0 type)
  _get_json_string(_step0_name PATH workflowPresets ${_workflow_index} steps 0 name)
  _get_json_string(_step1_type PATH workflowPresets ${_workflow_index} steps 1 type)
  _get_json_string(_step1_name PATH workflowPresets ${_workflow_index} steps 1 name)
  _get_json_string(_step2_type PATH workflowPresets ${_workflow_index} steps 2 type)
  _get_json_string(_step2_name PATH workflowPresets ${_workflow_index} steps 2 name)

  if(NOT _step0_type STREQUAL "configure" OR NOT _step0_name STREQUAL "${expected_configure}")
    message(FATAL_ERROR "Workflow '${workflow_name}' must configure preset '${expected_configure}'")
  endif()
  if(NOT _step1_type STREQUAL "build" OR NOT _step1_name STREQUAL "${expected_build}")
    message(FATAL_ERROR "Workflow '${workflow_name}' must build preset '${expected_build}'")
  endif()
  if(NOT _step2_type STREQUAL "test" OR NOT _step2_name STREQUAL "${expected_test}")
    message(FATAL_ERROR "Workflow '${workflow_name}' must test preset '${expected_test}'")
  endif()
endfunction()

function(_assert_package_tests_disabled preset_name)
  _find_named_preset("configurePresets" "${preset_name}" _preset_index)
  if(_preset_index EQUAL -1)
    message(FATAL_ERROR "configurePresets does not contain name='${preset_name}'")
  endif()

  _get_json_string(_package_tests_value OPTIONAL PATH configurePresets ${_preset_index} cacheVariables GENTEST_ENABLE_PACKAGE_TESTS)
  if(NOT _package_tests_value STREQUAL "OFF")
    message(FATAL_ERROR
      "Configure preset '${preset_name}' must set cacheVariables.GENTEST_ENABLE_PACKAGE_TESTS=OFF so CI diagnostics stay focused on the instrumented test executables")
  endif()
endfunction()

function(_find_matrix_row_by_preset preset_name out_row)
  string(REPLACE "\n" ";" _lines "${_workflow_content}")
  set(_match "")
  set(_current_row "")
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^          - ")
      if(NOT _current_row STREQUAL "")
        string(FIND "${_current_row}" "preset: ${preset_name}" _row_match)
        if(NOT _row_match EQUAL -1)
          set(_match "${_current_row}")
          break()
        endif()
      endif()
      set(_current_row "${_line}\n")
    elseif(NOT _current_row STREQUAL "")
      string(APPEND _current_row "${_line}\n")
    endif()
  endforeach()

  if(_match STREQUAL "" AND NOT _current_row STREQUAL "")
    string(FIND "${_current_row}" "preset: ${preset_name}" _row_match)
    if(NOT _row_match EQUAL -1)
      set(_match "${_current_row}")
    endif()
  endif()

  set(${out_row} "${_match}" PARENT_SCOPE)
endfunction()

function(_assert_row_contains preset_name expected_snippet requirement)
  _find_matrix_row_by_preset("${preset_name}" _row)
  if(_row STREQUAL "")
    message(FATAL_ERROR "Workflow matrix row for preset '${preset_name}' not found in ${_workflow_file}")
  endif()

  string(FIND "${_row}" "${expected_snippet}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR
      "Workflow matrix row for preset '${preset_name}' must ${requirement}.\n"
      "Observed row:\n${_row}")
  endif()
endfunction()

function(_assert_workflow_contains expected_snippet requirement)
  string(FIND "${_workflow_content}" "${expected_snippet}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR
      "Workflow ${_workflow_file} must ${requirement}.\n"
      "Missing snippet: ${expected_snippet}")
  endif()
endfunction()

function(_find_matrix_row_by_name_and_build_type row_name build_type out_row)
  string(REPLACE "\n" ";" _lines "${_workflow_content}")
  set(_match "")
  set(_current_row "")
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^          - ")
      if(NOT _current_row STREQUAL "")
        string(FIND "${_current_row}" "name: ${row_name}" _name_match)
        string(FIND "${_current_row}" "build_type: ${build_type}" _build_match)
        if(NOT _name_match EQUAL -1 AND NOT _build_match EQUAL -1)
          set(_match "${_current_row}")
          break()
        endif()
      endif()
      set(_current_row "${_line}\n")
    elseif(NOT _current_row STREQUAL "")
      string(APPEND _current_row "${_line}\n")
    endif()
  endforeach()

  if(_match STREQUAL "" AND NOT _current_row STREQUAL "")
    string(FIND "${_current_row}" "name: ${row_name}" _name_match)
    string(FIND "${_current_row}" "build_type: ${build_type}" _build_match)
    if(NOT _name_match EQUAL -1 AND NOT _build_match EQUAL -1)
      set(_match "${_current_row}")
    endif()
  endif()

  set(${out_row} "${_match}" PARENT_SCOPE)
endfunction()

function(_assert_named_row_contains row_name build_type expected_snippet requirement)
  _find_matrix_row_by_name_and_build_type("${row_name}" "${build_type}" _row)
  if(_row STREQUAL "")
    message(FATAL_ERROR
      "Workflow matrix row for name='${row_name}' build_type='${build_type}' not found in ${_workflow_file}")
  endif()

  string(FIND "${_row}" "${expected_snippet}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR
      "Workflow matrix row for name='${row_name}' build_type='${build_type}' must ${requirement}.\n"
      "Observed row:\n${_row}")
  endif()
endfunction()

foreach(_preset IN ITEMS coverage-system alusan-system tsan tsan-system)
  _require_preset("configurePresets" "${_preset}")
  _require_preset("buildPresets" "${_preset}")
  _require_preset("testPresets" "${_preset}")
  _require_preset("workflowPresets" "${_preset}")
  _assert_configure_preset("buildPresets" "${_preset}" "${_preset}")
  _assert_configure_preset("testPresets" "${_preset}" "${_preset}")
  _assert_workflow_steps("${_preset}" "${_preset}" "${_preset}" "${_preset}")
endforeach()

foreach(_ci_preset IN ITEMS coverage-system alusan-system tsan-system)
  _assert_package_tests_disabled("${_ci_preset}")
endforeach()

_assert_row_contains("coverage-system" "run_coverage: true" "mark run_coverage: true")
_assert_row_contains("coverage-system" "ctest_parallel: 1" "set ctest_parallel: 1")
_assert_row_contains("alusan-system" "build_type: ASan+UBSan" "set build_type: ASan+UBSan")
_assert_row_contains("alusan-system" "ctest_parallel: 2" "set ctest_parallel: 2")
_assert_row_contains("tsan-system" "build_type: TSan" "set build_type: TSan")
_assert_row_contains("tsan-system" "ctest_parallel: 2" "set ctest_parallel: 2")
_assert_workflow_contains("libclang-rt-\${{ matrix.clang_version }}-dev" "install the Clang compiler-rt development package so sanitizer presets can link")
_assert_workflow_contains("GENTEST_CODEGEN_JOBS=\${{ matrix.codegen_jobs }}" "export GENTEST_CODEGEN_JOBS from the matrix so Alpine CI exercises parallel codegen explicitly")

foreach(_alpine_build_type IN ITEMS debug release)
  _assert_named_row_contains("Alpine 3.21 • Clang 19" "${_alpine_build_type}" "codegen_jobs: 2"
    "set codegen_jobs: 2 so musl lanes exercise the parallel codegen path")
  _assert_named_row_contains("Alpine 3.23 • Clang 21" "${_alpine_build_type}" "codegen_jobs: 2"
    "set codegen_jobs: 2 so musl lanes exercise the parallel codegen path")
endforeach()
