# Compatibility targets and import repairs for LLVM/Clang package exports.

function(gentest_ensure_llvm_zstd_targets)
    find_package(zstd CONFIG QUIET)

    if(NOT TARGET zstd::libzstd)
        find_library(_gentest_zstd_library
            NAMES zstd libzstd.so.1 libzstd.so zstd_static
            PATHS
                /usr/lib64
                /usr/lib
                /lib64
                /lib
                /usr/lib/x86_64-linux-gnu
                /lib/x86_64-linux-gnu)
        if(_gentest_zstd_library)
            add_library(zstd::libzstd UNKNOWN IMPORTED)
            set_target_properties(zstd::libzstd PROPERTIES
                IMPORTED_LOCATION "${_gentest_zstd_library}")
        endif()
    endif()

    if(TARGET zstd::libzstd)
        foreach(_gentest_zstd_alias IN ITEMS zstd::libzstd_shared zstd::libzstd_static)
            if(NOT TARGET "${_gentest_zstd_alias}")
                add_library("${_gentest_zstd_alias}" INTERFACE IMPORTED)
                set_target_properties("${_gentest_zstd_alias}" PROPERTIES
                    INTERFACE_LINK_LIBRARIES zstd::libzstd)
            endif()
        endforeach()
    elseif(TARGET zstd::libzstd_shared AND NOT TARGET zstd::libzstd_static)
        add_library(zstd::libzstd_static INTERFACE IMPORTED)
        set_target_properties(zstd::libzstd_static PROPERTIES
            INTERFACE_LINK_LIBRARIES zstd::libzstd_shared)
    elseif(TARGET zstd::libzstd_static AND NOT TARGET zstd::libzstd_shared)
        add_library(zstd::libzstd_shared INTERFACE IMPORTED)
        set_target_properties(zstd::libzstd_shared PROPERTIES
            INTERFACE_LINK_LIBRARIES zstd::libzstd_static)
    endif()
endfunction()

macro(gentest_seed_llvm_prefix_from_config)
    unset(GENTEST_LLVM_DETECTED_PREFIX)
    unset(GENTEST_LLVM_DETECTED_PREFIX CACHE)
    set(_gentest_llvm_config_candidates)
    foreach(_v 23 22 21 20 19)
        list(APPEND _gentest_llvm_config_candidates "llvm-config-${_v}")
    endforeach()
    list(APPEND _gentest_llvm_config_candidates llvm-config)
    foreach(_cand IN LISTS _gentest_llvm_config_candidates)
        unset(_gentest_llvm_config_program)
        unset(_gentest_llvm_config_program CACHE)
        if(IS_ABSOLUTE "${_cand}" OR "${_cand}" MATCHES "[/\\\\]")
            if(EXISTS "${_cand}" AND NOT IS_DIRECTORY "${_cand}")
                set(_gentest_llvm_config_program "${_cand}")
            endif()
        else()
            find_program(_gentest_llvm_config_program NAMES "${_cand}" NO_CACHE)
        endif()
        if(NOT _gentest_llvm_config_program)
            continue()
        endif()
        execute_process(
            COMMAND "${_gentest_llvm_config_program}" --version
            RESULT_VARIABLE _gentest_llvm_config_version_rc
            OUTPUT_VARIABLE _gentest_llvm_config_version
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET)
        if(NOT _gentest_llvm_config_version_rc EQUAL 0)
            continue()
        endif()
        string(REGEX MATCH "^[0-9]+" _gentest_llvm_config_major "${_gentest_llvm_config_version}")
        if("${_gentest_llvm_config_major}" STREQUAL "" OR _gentest_llvm_config_major LESS 19)
            continue()
        endif()

        execute_process(
            COMMAND "${_gentest_llvm_config_program}" --cmakedir
            OUTPUT_VARIABLE _gentest_llvm_cmakedir
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET)
        if(_gentest_llvm_cmakedir AND EXISTS "${_gentest_llvm_cmakedir}/LLVMConfig.cmake")
            get_filename_component(_gentest_llvm_prefix "${_gentest_llvm_cmakedir}/../.." ABSOLUTE)
            list(PREPEND CMAKE_PREFIX_PATH "${_gentest_llvm_prefix}")
            set(GENTEST_LLVM_DETECTED_PREFIX "${_gentest_llvm_prefix}" CACHE INTERNAL
                "LLVM prefix detected from llvm-config" FORCE)
            break()
        endif()
    endforeach()
    unset(_gentest_llvm_config_candidates)
    unset(_gentest_llvm_config_program)
    unset(_gentest_llvm_config_version_rc)
    unset(_gentest_llvm_config_version)
    unset(_gentest_llvm_config_major)
endmacro()

macro(gentest_prepare_llvm_package_imports)
    set(CMAKE_DISABLE_FIND_PACKAGE_LibEdit ON)
    gentest_seed_llvm_prefix_from_config()
    gentest_ensure_llvm_zstd_targets()
endmacro()

function(gentest_get_llvm_package_major out_var package_name)
    set(_gentest_version "")
    if(package_name STREQUAL "LLVM")
        if(DEFINED LLVM_VERSION_MAJOR AND NOT "${LLVM_VERSION_MAJOR}" STREQUAL "")
            set(_gentest_version "${LLVM_VERSION_MAJOR}")
        elseif(DEFINED LLVM_PACKAGE_VERSION AND NOT "${LLVM_PACKAGE_VERSION}" STREQUAL "")
            set(_gentest_version "${LLVM_PACKAGE_VERSION}")
        elseif(DEFINED LLVM_DIR AND EXISTS "${LLVM_DIR}/LLVMConfigVersion.cmake")
            file(STRINGS "${LLVM_DIR}/LLVMConfigVersion.cmake" _gentest_version_line REGEX "^set\\(PACKAGE_VERSION")
            string(REGEX REPLACE ".*\"([0-9][^\"]*)\".*" "\\1" _gentest_version "${_gentest_version_line}")
        endif()
    elseif(package_name STREQUAL "Clang")
        if(DEFINED CLANG_VERSION_MAJOR AND NOT "${CLANG_VERSION_MAJOR}" STREQUAL "")
            set(_gentest_version "${CLANG_VERSION_MAJOR}")
        elseif(DEFINED CLANG_PACKAGE_VERSION AND NOT "${CLANG_PACKAGE_VERSION}" STREQUAL "")
            set(_gentest_version "${CLANG_PACKAGE_VERSION}")
        elseif(DEFINED Clang_DIR AND EXISTS "${Clang_DIR}/ClangConfigVersion.cmake")
            file(STRINGS "${Clang_DIR}/ClangConfigVersion.cmake" _gentest_version_line REGEX "^set\\(PACKAGE_VERSION")
            string(REGEX REPLACE ".*\"([0-9][^\"]*)\".*" "\\1" _gentest_version "${_gentest_version_line}")
        elseif(DEFINED LLVM_VERSION AND NOT "${LLVM_VERSION}" STREQUAL "")
            set(_gentest_version "${LLVM_VERSION}")
        endif()
    endif()

    set(_gentest_major "")
    if(NOT "${_gentest_version}" STREQUAL "")
        string(REGEX MATCH "^[0-9]+" _gentest_major "${_gentest_version}")
    endif()
    set(${out_var} "${_gentest_major}" PARENT_SCOPE)
endfunction()

function(gentest_require_llvm_package_minimum package_name minimum_major)
    gentest_get_llvm_package_major(_gentest_major "${package_name}")
    if("${_gentest_major}" STREQUAL "")
        message(FATAL_ERROR "gentest requires ${package_name} ${minimum_major}+ but could not determine the package version")
    endif()
    if(_gentest_major LESS minimum_major)
        message(FATAL_ERROR "gentest requires ${package_name} ${minimum_major}+; found ${package_name} ${_gentest_major}")
    endif()
endfunction()

function(gentest_patch_llvm_missing_diaguids)
    if(NOT WIN32)
        return()
    endif()

    file(GLOB _gentest_diaguids_candidates
        LIST_DIRECTORIES FALSE
        "C:/Program Files/Microsoft Visual Studio/2022/*/DIA SDK/lib/amd64/diaguids.lib"
        "C:/Program Files (x86)/Microsoft Visual Studio/2022/*/DIA SDK/lib/amd64/diaguids.lib"
        "C:/Program Files/Microsoft Visual Studio/2019/*/DIA SDK/lib/amd64/diaguids.lib"
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/*/DIA SDK/lib/amd64/diaguids.lib")
    if(_gentest_diaguids_candidates)
        list(GET _gentest_diaguids_candidates 0 _gentest_diaguids_lib)
    endif()

    foreach(_gentest_target IN LISTS ARGN)
        if(NOT TARGET "${_gentest_target}")
            continue()
        endif()
        get_target_property(_gentest_link_libs "${_gentest_target}" INTERFACE_LINK_LIBRARIES)
        if(NOT _gentest_link_libs OR _gentest_link_libs MATCHES "-NOTFOUND$")
            continue()
        endif()

        set(_gentest_patched_link_libs)
        set(_gentest_patched FALSE)
        foreach(_gentest_lib IN LISTS _gentest_link_libs)
            if(_gentest_lib MATCHES "(^|[/\\\\])diaguids\\.lib$" AND NOT EXISTS "${_gentest_lib}" AND DEFINED _gentest_diaguids_lib)
                list(APPEND _gentest_patched_link_libs "${_gentest_diaguids_lib}")
                set(_gentest_patched TRUE)
            else()
                list(APPEND _gentest_patched_link_libs "${_gentest_lib}")
            endif()
        endforeach()

        if(_gentest_patched)
            set_property(TARGET "${_gentest_target}" PROPERTY INTERFACE_LINK_LIBRARIES "${_gentest_patched_link_libs}")
            message(STATUS "gentest: patched ${_gentest_target} diaguids.lib: ${_gentest_diaguids_lib}")
        endif()
    endforeach()
endfunction()

function(gentest_imported_artifacts_exist out_var target_name)
    set(_ok TRUE)
    if(TARGET "${target_name}")
        get_target_property(_imported "${target_name}" IMPORTED)
        if(_imported)
            set(_artifact_props IMPORTED_LOCATION IMPORTED_IMPLIB)
            get_target_property(_imported_configs "${target_name}" IMPORTED_CONFIGURATIONS)
            if(_imported_configs AND NOT _imported_configs MATCHES "-NOTFOUND$")
                foreach(_config IN LISTS _imported_configs)
                    list(APPEND _artifact_props "IMPORTED_LOCATION_${_config}" "IMPORTED_IMPLIB_${_config}")
                endforeach()
            endif()

            foreach(_prop IN LISTS _artifact_props)
                get_target_property(_artifact "${target_name}" "${_prop}")
                if(_artifact AND NOT _artifact MATCHES "-NOTFOUND$" AND IS_ABSOLUTE "${_artifact}" AND NOT EXISTS "${_artifact}")
                    message(STATUS "gentest: skipping ${target_name}; ${_prop} does not exist: ${_artifact}")
                    set(_ok FALSE)
                    break()
                endif()
            endforeach()
        endif()
    endif()
    set(${out_var} "${_ok}" PARENT_SCOPE)
endfunction()

function(gentest_get_imported_config_artifacts target config out_location out_implib)
    string(TOUPPER "${config}" _gentest_config_upper)
    if(_gentest_config_upper STREQUAL "")
        get_target_property(_gentest_location "${target}" IMPORTED_LOCATION)
        get_target_property(_gentest_implib "${target}" IMPORTED_IMPLIB)
    else()
        get_target_property(_gentest_location "${target}" "IMPORTED_LOCATION_${_gentest_config_upper}")
        get_target_property(_gentest_implib "${target}" "IMPORTED_IMPLIB_${_gentest_config_upper}")
    endif()
    if(NOT _gentest_location OR _gentest_location MATCHES "-NOTFOUND$")
        set(_gentest_location "")
    endif()
    if(NOT _gentest_implib OR _gentest_implib MATCHES "-NOTFOUND$")
        set(_gentest_implib "")
    endif()
    set(${out_location} "${_gentest_location}" PARENT_SCOPE)
    set(${out_implib} "${_gentest_implib}" PARENT_SCOPE)
endfunction()

function(gentest_ensure_imported_config_artifacts target config)
    string(TOUPPER "${config}" _gentest_config_upper)
    gentest_get_imported_config_artifacts("${target}" "${_gentest_config_upper}"
        _gentest_existing_location _gentest_existing_implib)
    if(_gentest_existing_location OR _gentest_existing_implib)
        return()
    endif()

    set(_gentest_fallback_configs RELEASE RELWITHDEBINFO MINSIZEREL NOCONFIG "")
    foreach(_gentest_fallback_config IN LISTS _gentest_fallback_configs)
        string(TOUPPER "${_gentest_fallback_config}" _gentest_fallback_upper)
        if(_gentest_fallback_upper STREQUAL _gentest_config_upper)
            continue()
        endif()

        gentest_get_imported_config_artifacts("${target}" "${_gentest_fallback_upper}"
            _gentest_fallback_location _gentest_fallback_implib)
        if(NOT _gentest_fallback_location AND NOT _gentest_fallback_implib)
            continue()
        endif()

        if(_gentest_fallback_location)
            set_property(TARGET "${target}" PROPERTY
                "IMPORTED_LOCATION_${_gentest_config_upper}" "${_gentest_fallback_location}")
        endif()
        if(_gentest_fallback_implib)
            set_property(TARGET "${target}" PROPERTY
                "IMPORTED_IMPLIB_${_gentest_config_upper}" "${_gentest_fallback_implib}")
        endif()
        get_target_property(_gentest_imported_configs "${target}" IMPORTED_CONFIGURATIONS)
        if(NOT _gentest_imported_configs OR _gentest_imported_configs MATCHES "-NOTFOUND$")
            set(_gentest_imported_configs "")
        endif()
        list(APPEND _gentest_imported_configs "${_gentest_config_upper}")
        list(REMOVE_DUPLICATES _gentest_imported_configs)
        set_property(TARGET "${target}" PROPERTY IMPORTED_CONFIGURATIONS "${_gentest_imported_configs}")
        message(STATUS "gentest: patched ${target} ${_gentest_config_upper} imported artifacts from ${_gentest_fallback_upper}")
        return()
    endforeach()
endfunction()
