if(NOT DEFINED INPUT OR "${INPUT}" STREQUAL "")
    message(FATAL_ERROR "WriteModuleRegistrationImpl.cmake: INPUT is required")
endif()
if(NOT DEFINED OUTPUT OR "${OUTPUT}" STREQUAL "")
    message(FATAL_ERROR "WriteModuleRegistrationImpl.cmake: OUTPUT is required")
endif()
if(NOT DEFINED HEADER_NAME OR "${HEADER_NAME}" STREQUAL "")
    message(FATAL_ERROR "WriteModuleRegistrationImpl.cmake: HEADER_NAME is required")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/GentestCodegen.cmake")

set(_gentest_include_dirs "")
if(DEFINED INCLUDE_DIRS_SERIALIZED AND NOT "${INCLUDE_DIRS_SERIALIZED}" STREQUAL "")
    string(REPLACE "__GENTEST_LISTSEP__" ";" _gentest_include_dirs "${INCLUDE_DIRS_SERIALIZED}")
endif()

set(_gentest_defines "")
if(DEFINED DEFINES_SERIALIZED AND NOT "${DEFINES_SERIALIZED}" STREQUAL "")
    string(REPLACE "__GENTEST_LISTSEP__" ";" _gentest_defines "${DEFINES_SERIALIZED}")
endif()

_gentest_extract_module_name("${INPUT}" _gentest_module_name
    ${_gentest_include_dirs} __gentest_defines__ ${_gentest_defines})

get_filename_component(_gentest_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_gentest_output_dir}")

set(_gentest_registration_impl_content
"// This file is auto-generated by gentest (CMake module registration shim).\n\
// Do not edit manually.\n\
\n\
module;\n\
\n\
#include <array>\n\
#include <fmt/format.h>\n\
#include <memory>\n\
#include <span>\n\
#include <string>\n\
#include <string_view>\n\
#include <type_traits>\n\
#include <utility>\n\
#include \"gentest/runner.h\"\n\
#include \"gentest/fixture.h\"\n\
\n\
module ${_gentest_module_name};\n\
\n\
#if !defined(GENTEST_CODEGEN) && __has_include(\"${HEADER_NAME}\")\n\
#define GENTEST_TU_REGISTRATION_HEADER_NO_PREAMBLE 1\n\
#include \"${HEADER_NAME}\"\n\
#undef GENTEST_TU_REGISTRATION_HEADER_NO_PREAMBLE\n\
#endif\n")

set(_gentest_write_output TRUE)
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _gentest_existing_output)
    if(_gentest_existing_output STREQUAL _gentest_registration_impl_content)
        set(_gentest_write_output FALSE)
    endif()
endif()

if(_gentest_write_output)
    file(WRITE "${OUTPUT}" "${_gentest_registration_impl_content}")
endif()
