name: Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bazel:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.31.x'

      - name: Setup LLVM (20)
        uses: llvm/actions/setup-llvm@v1
        with:
          version: '20'

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libfmt-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja fmt

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run Bazel tests (unit)
        shell: bash
        env:
          CMAKE_PREFIX_PATH: "$LLVM_PATH;${{ env.CMAKE_PREFIX_PATH }}"
        run: |
          bazel test //:gentest_unit_bazel

