name: CMake macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.31.x'

      - name: Setup LLVM (20)
        uses: llvm/actions/setup-llvm@v1
        with:
          version: '20'

      - name: Install deps (Homebrew)
        run: |
          brew update
          brew install ninja fmt

      - name: Configure (Debug)
        shell: bash
        run: |
          cmake -G Ninja -S . -B build/ci \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DLLVM_DIR="$LLVM_PATH/lib/cmake/llvm" \
            -DClang_DIR="$LLVM_PATH/lib/cmake/clang"

      - name: Build
        run: cmake --build build/ci -j 2

      - name: Test
        run: ctest --test-dir build/ci --output-on-failure -j 2

